import { createContext, useContext, useState, useCallback, ReactNode } from "react";

export type Language = "ja" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  ja: {
    // Nav & Layout
    "nav.home": "トップ",
    "nav.analysis": "分析",
    "nav.promotion": "販促",
    "nav.management": "管理",
    "nav.diagnosis": "診断",
    "nav.areaAnalysis": "商圏・出店分析",
    "nav.locationMatch": "エリア適性",
    "nav.storeCandidates": "出店候補地管理",
    "nav.mediaPlan": "統合媒体プラン",
    "nav.adProposal": "広告提案",
    "nav.flyerPlan": "チラシ設計",
    "nav.agencyDashboard": "案件管理",
    "nav.report": "統合レポート",
    "nav.diagnosisList": "診断一覧",
    "nav.storeInput": "店舗入力（診断）",
    "nav.logout": "ログアウト",
    "nav.login": "ログイン",
    "footer.copyright": "© 2024 MapBoost AI",
    "footer.description": "ローカルマーケティング分析ツール — 地域分析・出店分析・広告提案・チラシ配布設計",

    // Index / Hero
    "hero.badge": "マップ連動型 店舗集客AI",
    "hero.title1": "あなたのお店に合う",
    "hero.title2": "集客施策を、",
    "hero.title3": "数分で提案",
    "hero.description": "店舗情報を入力するだけで、商圏・客層・競合をふまえた集客プランをAIが作成します。",
    "hero.cta": "無料で診断する",
    "hero.loginBtn": "ログイン",
    "hero.visitRate": "来店率",
    "hero.awareness": "認知度",
    "features.badge": "主な機能",
    "features.title": "MapBoost AI でできること",
    "features.description": "店舗情報を入力するだけで、6つの分析・提案を自動で行います。",
    "feature.diagnosis.title": "集客診断",
    "feature.diagnosis.desc": "商圏・客層・競合を分析し、店舗の強み・弱みを可視化します。",
    "feature.area.title": "商圏分析",
    "feature.area.desc": "半径1〜5kmの人口統計・年齢構成・世帯構成をAIが分析。",
    "feature.candidates.title": "出店候補地管理",
    "feature.candidates.desc": "出店候補地を登録・管理し、商圏スコアで比較評価できます。",
    "feature.media.title": "媒体プラン",
    "feature.media.desc": "Meta・Google・チラシの最適な予算配分とターゲットをAIが提案。",
    "feature.agency.title": "案件管理ダッシュボード",
    "feature.agency.desc": "クライアント・店舗の分析案件を一覧で管理。ステータスも一目瞭然。",
    "feature.report.title": "統合レポート",
    "feature.report.desc": "商圏分析・施策・広告・チラシを1ページに集約。PDF出力も対応。",
    "steps.title": "かんたん4ステップ",
    "steps.description": "入力から施策実行まで、わずか数分で完了します。",
    "step1.title": "店舗情報を入力",
    "step1.desc": "業種・住所・強み・悩みなどを入力",
    "step2.title": "AIが分析・提案",
    "step2.desc": "数秒で診断結果と施策を表示",
    "step3.title": "販促文を生成",
    "step3.desc": "各媒体向けの文面をワンクリック作成",
    "step4.title": "実行 & 改善",
    "step4.desc": "KPIを見ながら施策を実行・改善",
    "cta.title": "まずは無料で診断してみましょう",
    "cta.description": "所要時間は約3分。登録後すぐに始められます。",

    // Auth
    "auth.title": "MapBoost AI",
    "auth.subtitle": "アカウントにログインまたは新規登録",
    "auth.loginTab": "ログイン",
    "auth.signupTab": "新規登録",
    "auth.email": "メールアドレス",
    "auth.password": "パスワード",
    "auth.passwordHint": "パスワード（6文字以上）",
    "auth.loginBtn": "ログイン",
    "auth.signupBtn": "アカウント作成",
    "auth.processing": "処理中…",
    "auth.or": "または",
    "auth.googleLogin": "Googleでログイン",
    "auth.googleSignup": "Googleでアカウント作成",
    "auth.loginFailed": "ログインに失敗しました。メールアドレスとパスワードをご確認ください。",
    "auth.signupSuccess": "確認メールを送信しました。メールをご確認ください。",
    "auth.googleFailed": "Googleログインに失敗しました",
    "loading": "読み込み中...",

    // Store Input
    "store.badge": "店舗情報入力",
    "store.title": "店舗の情報を教えてください",
    "store.description": "入力内容をもとに、AIが集客診断と施策を提案します。",
    "store.basicInfo": "基本情報",
    "store.basicInfoDesc": "できるだけ詳しく入力いただくと、より精度の高い診断が可能です。",
    "store.name": "店舗名",
    "store.industry": "業種",
    "store.address": "住所",
    "store.station": "最寄駅",
    "store.target": "ターゲット層",
    "store.strengths": "店の強み",
    "store.concerns": "現在の悩み",
    "store.budget": "月の広告・販促予算",
    "store.competitors": "競合店舗",
    "store.media": "利用したい媒体（複数選択可）",
    "store.submit": "診断を開始する",
    "store.submitting": "AIが分析中…（30秒ほどかかります）",
    "store.aiStarted": "AIが診断を開始しました…",
    "store.completed": "診断が完了しました！",
    "store.failed": "診断の開始に失敗しました",

    // Diagnosis
    "diag.badge": "診断結果",
    "diag.title": "の集客診断",
    "diag.subtitle": "AIが分析した結果をもとに、最適な施策を提案します。",
    "diag.notFound": "診断結果が見つかりませんでした",
    "diag.generating": "診断結果を生成中です…",
    "diag.backToDashboard": "ダッシュボードに戻る",
    "diag.strengths": "店舗の強み",
    "diag.weaknesses": "弱み・課題",
    "diag.targetCustomers": "狙うべき客層",
    "diag.differentiation": "差別化ポイント",
    "diag.bottlenecks": "集客ボトルネック",
    "diag.bottlenecksDesc": "現在の集客を妨げている主な要因",
    "diag.actions": "今すぐやるべき施策",
    "diag.estimatedCost": "概算コスト",
    "diag.difficulty": "難易度",
    "diag.expectedEffect": "効果の目安",
    "diag.pdfExport": "PDF出力",
    "diag.viewPromo": "販促文を見る",
    "diag.viewKpi": "KPI設計を見る",

    // PromoText
    "promo.title": "販促文の自動生成",
    "promo.subtitle": "— 媒体ごとの販促文",
    "promo.generating": "販促文を生成中です…",
    "promo.dataNotFound": "データが見つかりません",
    "promo.copy": "コピー",
    "promo.copied": "クリップボードにコピーしました",
    "promo.softer": "やわらかく",
    "promo.stronger": "力強く",
    "promo.alternative": "別案を出す",
    "promo.regenerate": "販促文を再生成",
    "promo.regenerated": "販促文を再生成しました",
    "promo.regenerateFailed": "再生成に失敗しました",
    "promo.adjustedSoft": "やわらかく調整しました",
    "promo.adjustedStrong": "力強く調整しました",
    "promo.adjustedAlt": "別案調整しました",
    "promo.adjustFailed": "調整に失敗しました",

    // KPI
    "kpi.badge": "KPI設計",
    "kpi.title": "のKPI設計",
    "kpi.subtitle": "施策の効果を測定するための指標と目標値",
    "kpi.generating": "KPI設計を生成中です…",
    "kpi.target": "目標値",
    "kpi.measurement": "測定方法",
    "kpi.frequency": "確認頻度",

    // Dashboard
    "dash.badge": "ダッシュボード",
    "dash.title": "診断案件の管理",
    "dash.subtitle": "過去の診断レポートの確認・管理ができます。",
    "dash.newDiagnosis": "新しい診断を作成",
    "dash.noDiagnosis": "診断がまだありません",
    "dash.noDiagnosisDesc": "店舗情報を入力して、AIによる集客診断を始めましょう。",
    "dash.createFirst": "最初の診断を作成",
    "dash.totalDiagnoses": "総診断数",
    "dash.completed": "完了済み",
    "dash.thisMonth": "今月の診断",
    "dash.latest": "直近の診断",
    "dash.trendTitle": "診断推移（直近6ヶ月）",
    "dash.noTrendData": "診断データがまだありません",
    "dash.totalCount": "総診断数",
    "dash.completedCount": "完了済み",
    "dash.report": "レポート",
    "dash.promoText": "販促文",
    "dash.status.completed": "完了",
    "dash.status.processing": "処理中",
    "dash.status.pending": "作成中",
    "dash.status.error": "エラー",
    "dash.strengthsCount": "強み",
    "dash.actionsCount": "施策",
    "dash.createdOn": "に作成",

    // Area Analysis
    "area.badge": "地域分析",
    "area.title": "商圏・出店分析",
    "area.subtitle": "住所を入力して、AIが地域の人口統計・市場性を分析します。",
    "area.tabArea": "商圏分析",
    "area.tabOpening": "出店分析",
    "area.addressLabel": "住所・エリア名",
    "area.radiusLabel": "商圏半径",
    "area.industryLabel": "業種",
    "area.industryOptional": "（任意）",
    "area.analyze": "AIで分析する",
    "area.analyzing": "分析中...",
    "area.pdfDownload": "PDFダウンロード",
    "area.realData": "実データ",
    "area.aiEstimate": "AI推定値",
    "area.censusTitle": "国勢調査データ",
    "area.totalPopulation": "総人口",
    "area.totalHouseholds": "世帯数",
    "area.dataSource": "データソース",
    "area.ageComposition": "年齢構成（実データ）",
    "area.areaLabel": "エリア",
    "area.estPopulation": "推定人口",
    "area.estHouseholds": "推定世帯数",
    "area.radius": "商圏半径",
    "area.characteristics": "エリアの特徴",
    "area.primaryTarget": "主要ターゲット",
    "area.ageDistribution": "年齢構成",
    "area.householdComposition": "世帯構成",
    "area.suitableIndustries": "向いている業種",
    "area.unsuitableIndustries": "不利な業種",
    "area.visitMotivations": "来店動機の傾向",
    "area.competitiveEnv": "競合環境",
    "area.scoreBreakdown": "スコア内訳",
    "area.successProb": "成功確率",
    "area.targetCustomer": "想定ターゲット",
    "area.unitPrice": "想定客単価",
    "area.visitFreq": "想定来店頻度",
    "area.riskFactors": "リスク要因",
    "area.improvements": "改善アドバイス",
    "area.risk": "リスク",
    "area.countermeasure": "対策",
    "area.analysisComplete": "分析が完了しました（AI推定値）",
    "area.censusAnalysisComplete": "国勢調査データを基に分析が完了しました",
    "area.analysisFailed": "分析に失敗しました",
    "area.enterAddress": "住所を入力してください",
    "area.enterIndustry": "業種を入力してください",
    "area.population": "人口",
    "area.proportion": "割合",
    "area.radius1km": "半径1km",
    "area.radius3km": "半径3km",
    "area.radius5km": "半径5km",

    // Flyer Plan
    "flyer.badge": "チラシ配布設計",
    "flyer.title": "チラシ配布プランナー",
    "flyer.subtitle": "AIが最適な配布エリア・部数・キャッチコピーを自動設計します。",
    "flyer.storeLocation": "店舗所在地",
    "flyer.industry": "業種",
    "flyer.storeName": "店舗名（任意）",
    "flyer.budget": "予算目安（任意）",
    "flyer.target": "ターゲット層（任意）",
    "flyer.generate": "AIで配布計画を作成",
    "flyer.generating": "計画生成中...",
    "flyer.pdfDownload": "PDFダウンロード",
    "flyer.summary": "配布計画の概要",
    "flyer.totalQuantity": "合計部数",
    "flyer.totalCost": "合計費用",
    "flyer.expectedResponse": "期待反応率",
    "flyer.expectedROI": "期待ROI",
    "flyer.distributionPlan": "配布エリア計画",
    "flyer.priority": "優先度",
    "flyer.estHouseholds": "推定世帯",
    "flyer.targetDesc": "ターゲット",
    "flyer.areaDistribution": "エリア別配布部数",
    "flyer.costBreakdown": "費用内訳",
    "flyer.printUnit": "印刷単価",
    "flyer.distUnit": "配布単価",
    "flyer.printTotal": "印刷費合計",
    "flyer.distTotal": "配布費合計",
    "flyer.total": "合計",
    "flyer.timing": "配布タイミング",
    "flyer.bestDays": "最適な曜日",
    "flyer.bestTimeSlots": "最適な時間帯",
    "flyer.frequency": "推奨頻度",
    "flyer.seasonalAdvice": "季節アドバイス",
    "flyer.catchcopies": "キャッチコピー案",
    "flyer.designTips": "デザインアドバイス",
    "flyer.completed": "チラシ配布計画が完成しました",
    "flyer.failed": "計画の生成に失敗しました",
    "flyer.copied": "コピーしました",
    "flyer.quantity": "部数",
    "flyer.households": "世帯数",

    // Ad Proposal
    "ad.badge": "広告提案",
    "ad.title": "広告プランナー",
    "ad.subtitle": "AIがGoogle広告・Meta広告の最適プランを自動設計します。",
    "ad.storeLocation": "店舗所在地",
    "ad.industry": "業種",
    "ad.storeName": "店舗名（任意）",
    "ad.budget": "月間広告予算（任意）",
    "ad.target": "ターゲット層（任意）",
    "ad.generate": "AIで広告提案を作成",
    "ad.generating": "提案生成中...",
    "ad.pdfDownload": "PDFダウンロード",
    "ad.strategySummary": "広告戦略の概要",
    "ad.recommendedPlatform": "推奨プラットフォーム",
    "ad.monthlyBudget": "月間合計予算",
    "ad.expectedROAS": "期待ROAS",
    "ad.campaignType": "キャンペーンタイプ",
    "ad.dailyBudget": "日予算",
    "ad.expectedCTR": "期待CTR",
    "ad.keywords": "推奨キーワード",
    "ad.adCopies": "広告文案",
    "ad.campaignObjective": "キャンペーン目的",
    "ad.expectedCPM_CTR": "期待CPM / CTR",
    "ad.targetAudience": "ターゲットオーディエンス",
    "ad.adCreatives": "広告クリエイティブ案",
    "ad.strategyTips": "総合戦略・運用Tips",
    "ad.recommend": "推奨",
    "ad.completed": "広告提案が完成しました",
    "ad.failed": "提案の生成に失敗しました",
    "ad.copied": "コピーしました",

    // Location Match
    "loc.badge": "エリアマッチング",
    "loc.title": "ロケーションマッチング",
    "loc.subtitle": "あなたのサービスに最適な出店・広告・チラシ配布エリアをAIが提案します。",
    "loc.industry": "業種",
    "loc.budgetScale": "予算規模（任意）",
    "loc.preferredArea": "希望エリア・現在地（任意）",
    "loc.target": "ターゲット層（任意）",
    "loc.serviceDesc": "サービス内容",
    "loc.otherPrefs": "その他の条件（任意）",
    "loc.generate": "AIでエリアマッチング",
    "loc.generating": "エリア分析中...",
    "loc.pdfDownload": "PDFダウンロード",
    "loc.analysisSummary": "分析結果の概要",
    "loc.aiRecommendation": "AIの最終推奨",
    "loc.initialInvestment": "初期投資目安",
    "loc.areaRanking": "推奨エリアランキング",
    "loc.estPopulation": "推定人口",
    "loc.mainTarget": "主要ターゲット",
    "loc.competitionLevel": "競合密度",
    "loc.rentEstimate": "家賃相場",
    "loc.monthlyCustomers": "月間見込み顧客数",
    "loc.strengths": "強み",
    "loc.risks": "リスク",
    "loc.storeTab": "出店",
    "loc.adTab": "広告",
    "loc.flyerTab": "チラシ",
    "loc.comparisonTable": "エリア比較表",
    "loc.area": "エリア",
    "loc.score": "スコア",
    "loc.competition": "競合",
    "loc.targetFit": "ターゲット適合",
    "loc.costEfficiency": "コスト効率",
    "loc.growthPotential": "成長性",
    "loc.actionPlan": "具体的アクションプラン",
    "loc.completed": "エリアマッチング分析が完了しました",
    "loc.failed": "分析に失敗しました",
    "loc.enterIndustry": "業種を入力してください",
    "loc.enterService": "サービス内容を入力してください",

    // Media Plan
    "media.badge": "媒体プラン",
    "media.title": "統合媒体プランナー",
    "media.subtitle": "Google広告・Meta広告・チラシ配布を一括でプランニングします。",
    "media.storeLocation": "店舗所在地",
    "media.industry": "業種",
    "media.storeName": "店舗名（任意）",
    "media.budget": "月間予算（任意）",
    "media.target": "ターゲット層（任意）",
    "media.generate": "統合媒体プランを作成",
    "media.generating": "プラン生成中...",
    "media.pdfDownload": "PDFダウンロード",
    "media.noMetaData": "Meta広告データがありません",
    "media.noGoogleData": "Google広告データがありません",
    "media.noFlyerData": "チラシデータがありません",
    "media.completed": "媒体プランが完成しました",
    "media.failed": "プラン生成に失敗しました",
    "media.distributionArea": "配布エリア",
    "media.distributionTiming": "配布タイミング",
    "media.catchcopies": "キャッチコピー案",

    // Agency Dashboard
    "agency.badge": "代理店ダッシュボード",
    "agency.title": "案件管理",
    "agency.subtitle": "すべての診断・候補地を一元管理します。",
    "agency.newDiagnosis": "新規診断",
    "agency.addCandidate": "候補地追加",
    "agency.totalProjects": "総案件数",
    "agency.diagCompleted": "診断完了",
    "agency.processing": "処理中",
    "agency.storeCandidates": "出店候補地",
    "agency.searchPlaceholder": "店舗名・業種で検索...",
    "agency.statusFilter": "ステータス",
    "agency.all": "すべて",
    "agency.completed": "完了",
    "agency.pending": "処理中",
    "agency.draft": "下書き",
    "agency.noResults": "該当する案件がありません",
    "agency.type": "種別",
    "agency.storeName": "店舗名",
    "agency.industry": "業種",
    "agency.date": "分析日時",
    "agency.status": "ステータス",
    "agency.action": "操作",
    "agency.details": "詳細",
    "agency.typeDiagnosis": "診断",
    "agency.typeCandidate": "候補地",

    // Report
    "report.badge": "統合レポート",
    "report.title": "分析レポート",
    "report.subtitle": "商圏分析・推奨施策・広告配分・チラシ出稿案を1ページで確認できます。",
    "report.address": "住所",
    "report.industry": "業種",
    "report.storeName": "店舗名（任意）",
    "report.budget": "月間予算（任意）",
    "report.target": "ターゲット（任意）",
    "report.generate": "統合レポートを作成",
    "report.generating": "レポート生成中...",
    "report.pdfDownload": "PDFダウンロード",
    "report.failed": "レポート生成に失敗しました",
    "report.aiRunning": "3つのAI分析を同時実行中...",
    "report.tradeArea": "商圏分析結果",
    "report.recommendations": "推奨施策",
    "report.adBudget": "広告予算配分",
    "report.flyerPlan": "チラシ出稿案",
    "report.completed": "レポートが完成しました",
    "report.area": "エリア",
    "report.estPopulation": "推定人口",
    "report.estHouseholds": "推定世帯数",
    "report.mainTarget": "主要ターゲット",
    "report.competitiveEnv": "競合環境",
    "report.monthlyBudget": "月間予算",
    "report.monthlyTotal": "月間合計予算",

    // Store Candidates
    "cand.badge": "出店候補地管理",
    "cand.title": "出店候補地の登録",
    "cand.subtitle": "出店を検討しているエリアを登録し、商圏分析や媒体プランに活用できます。",
    "cand.addNew": "新しい候補地を追加",
    "cand.closeForm": "フォームを閉じる",
    "cand.formTitle": "候補地情報を入力",
    "cand.formDesc": "できるだけ詳しく入力すると、分析精度が向上します。",
    "cand.storeName": "店舗名",
    "cand.industry": "業種",
    "cand.address": "住所",
    "cand.latitude": "緯度（任意）",
    "cand.longitude": "経度（任意）",
    "cand.memo": "出店候補地メモ（任意）",
    "cand.register": "候補地を登録",
    "cand.registering": "登録中...",
    "cand.registered": "出店候補地を登録しました",
    "cand.deleted": "候補地を削除しました",
    "cand.fetchFailed": "データの取得に失敗しました",
    "cand.empty": "候補地がまだありません",
    "cand.emptyDesc": "出店を検討しているエリアを登録しましょう。",
    "cand.addFirst": "最初の候補地を追加",

    // NotFound
    "notFound.title": "ページが見つかりません",
    "notFound.back": "ホームに戻る",

    // Common
    "common.required": "必須",
    "common.optional": "任意",
    "common.enterAddress": "住所を入力してください",
    "common.enterIndustry": "業種を入力してください",
    "common.copied": "コピーしました",

    // Pricing
    "pricing.badge": "料金プラン",
    "pricing.title": "プランを選択",
    "pricing.subtitle": "無料で始めて、必要に応じてアップグレードできます。",
    "pricing.month": "月",
    "pricing.currentPlan": "現在のプラン",
    "pricing.upgrade": "Proにアップグレード",
    "pricing.manage": "サブスクリプション管理",
    "pricing.error": "エラーが発生しました。もう一度お試しください。",
    "pricing.free.name": "フリー",
    "pricing.free.desc": "主要機能を無料でお試し",
    "pricing.free.f1": "月3回までの診断",
    "pricing.free.f2": "基本的な商圏分析",
    "pricing.free.f3": "販促テキスト生成",
    "pricing.free.f4": "PDFエクスポート",
    "pricing.pro.name": "プロ",
    "pricing.pro.desc": "本格運用に最適な無制限プラン",
    "pricing.pro.f1": "無制限の診断・分析",
    "pricing.pro.f2": "国勢調査データ連携の商圏分析",
    "pricing.pro.f3": "チラシ設計",
    "pricing.pro.f4": "広告提案の自動生成",
    "pricing.pro.f5": "統合媒体プラン",
    "pricing.pro.f6": "優先サポート",
    "nav.pricing": "料金プラン",

    // Area Analysis
    "area.badge": "地域分析",
    "area.title": "商圏・出店分析",
    "area.subtitle": "住所を入力して、AIが地域の人口統計・市場性を分析します。",
    "area.tabArea": "商圏分析",
    "area.tabOpening": "出店分析",
    "area.address": "住所・エリア名",
    "area.addressPh": "例: 東京都渋谷区神南1丁目",
    "area.radius": "商圏半径",
    "area.industry": "業種",
    "area.industryOptional": "（任意）",
    "area.industryPh": "例: カフェ、学習塾、美容院",
    "area.analyzing": "分析中...",
    "area.analyze": "AIで分析する",
    "area.pdfDownload": "PDFダウンロード",
    "area.realData": "実データ",
    "area.aiEstimate": "AI推定値",
    "area.censusTitle": "国勢調査データ",
    "area.source": "出典",
    "area.areaCode": "地域コード",
    "area.totalPop": "総人口",
    "area.households": "世帯数",
    "area.dataSource": "データソース",
    "area.ageComp": "年齢構成",
    "area.ageCompReal": "年齢構成（実データ）",
    "area.areaLabel": "エリア",
    "area.estPop": "推定人口",
    "area.estHouseholds": "推定世帯数",
    "area.radiusLabel": "商圏半径",
    "area.areaFeatures": "エリアの特徴",
    "area.mainTarget": "主要ターゲット",
    "area.householdComp": "世帯構成",
    "area.suitableInd": "向いている業種",
    "area.unsuitableInd": "不利な業種",
    "area.visitMotivations": "来店動機の傾向",
    "area.competition": "競合環境",
    "area.successProb": "成功確率",
    "area.scoreBreakdown": "スコア内訳",
    "area.targetCustomer": "想定ターゲット",
    "area.unitPrice": "想定客単価",
    "area.visitFreq": "想定来店頻度",
    "area.riskFactors": "リスク要因",
    "area.improvements": "改善アドバイス",
    "area.risk": "リスク",
    "area.countermeasure": "対策",
    "area.enterAddress": "住所を入力してください",
    "area.enterIndustry": "業種を入力してください",
    "area.analysisComplete": "分析が完了しました",
    "area.analysisCompleteReal": "国勢調査データを基に分析が完了しました",
    "area.analysisCompleteFallback": "分析が完了しました（AI推定値）",
    "area.analysisFailed": "分析に失敗しました",
    "area.radius1km": "半径1km",
    "area.radius3km": "半径3km",
    "area.radius5km": "半径5km",
    "area.people": "人",
    "area.householdsUnit": "世帯",
    "area.population": "人口",
    "area.percentage": "割合",

    // Flyer Plan
    "flyer.badge": "チラシ配布設計",
    "flyer.title": "チラシ配布プランナー",
    "flyer.subtitle": "AIが最適な配布エリア・部数・キャッチコピーを自動設計します。",
    "flyer.storeLocation": "店舗所在地",
    "flyer.industry": "業種",
    "flyer.storeName": "店舗名（任意）",
    "flyer.budget": "予算目安（任意）",
    "flyer.targetAudience": "ターゲット層（任意）",
    "flyer.generating": "計画生成中...",
    "flyer.generate": "AIで配布計画を作成",
    "flyer.summary": "配布計画の概要",
    "flyer.totalQty": "合計部数",
    "flyer.totalCost": "合計費用",
    "flyer.expectedResponse": "期待反応率",
    "flyer.expectedROI": "期待ROI",
    "flyer.distAreas": "配布エリア計画",
    "flyer.priority": "優先度",
    "flyer.estHouseholds": "推定世帯",
    "flyer.targetDesc": "ターゲット",
    "flyer.areaDistChart": "エリア別配布部数",
    "flyer.costBreakdown": "費用内訳",
    "flyer.printUnit": "印刷単価",
    "flyer.distUnit": "配布単価",
    "flyer.printTotal": "印刷費合計",
    "flyer.distTotal": "配布費合計",
    "flyer.total": "合計",
    "flyer.timing": "配布タイミング",
    "flyer.bestDays": "最適な曜日",
    "flyer.bestTime": "最適な時間帯",
    "flyer.frequency": "推奨頻度",
    "flyer.seasonalTips": "季節アドバイス",
    "flyer.catchcopies": "キャッチコピー案",
    "flyer.designTips": "デザインアドバイス",
    "flyer.copies": "部",
    "flyer.perSheet": "/枚",
    "flyer.planComplete": "チラシ配布計画が完成しました",
    "flyer.planFailed": "計画の生成に失敗しました",

    // Ad Proposal
    "ad.badge": "広告提案",
    "ad.title": "広告プランナー",
    "ad.subtitle": "AIがGoogle広告・Meta広告の最適プランを自動設計します。",
    "ad.storeLocation": "店舗所在地",
    "ad.industry": "業種",
    "ad.storeName": "店舗名（任意）",
    "ad.monthlyBudget": "月間広告予算（任意）",
    "ad.targetAudience": "ターゲット層（任意）",
    "ad.generating": "提案生成中...",
    "ad.generate": "AIで広告提案を作成",
    "ad.strategySummary": "広告戦略の概要",
    "ad.recPlatform": "推奨プラットフォーム",
    "ad.monthlyTotal": "月間合計予算",
    "ad.expectedROAS": "期待ROAS",
    "ad.googleCPA": "Google CPA",
    "ad.googleAds": "Google 広告",
    "ad.metaAds": "Meta 広告",
    "ad.campaignType": "キャンペーンタイプ",
    "ad.dailyBudget": "日予算",
    "ad.expectedCTR": "期待CTR",
    "ad.recKeywords": "推奨キーワード",
    "ad.adCopies": "広告文案",
    "ad.campaignObj": "キャンペーン目的",
    "ad.expectedCPM_CTR": "期待CPM / CTR",
    "ad.targetAudiences": "ターゲットオーディエンス",
    "ad.age": "年齢",
    "ad.gender": "性別",
    "ad.adCreatives": "広告クリエイティブ案",
    "ad.overallStrategy": "総合戦略・運用Tips",
    "ad.recommended": "推奨",
    "ad.proposalComplete": "広告提案が完成しました",
    "ad.proposalFailed": "提案の生成に失敗しました",

    // Location Match
    "loc.badge": "エリアマッチング",
    "loc.title": "ロケーションマッチング",
    "loc.subtitle": "あなたのサービスに最適な出店・広告・チラシ配布エリアをAIが提案します。",
    "loc.industry": "業種",
    "loc.budgetScale": "予算規模（任意）",
    "loc.preferredArea": "希望エリア・現在地（任意）",
    "loc.targetAudience": "ターゲット層（任意）",
    "loc.serviceDesc": "サービス内容",
    "loc.otherConditions": "その他の条件（任意）",
    "loc.analyzing": "エリア分析中...",
    "loc.analyze": "AIでエリアマッチング",
    "loc.analysisSummary": "分析結果の概要",
    "loc.aiFinalRec": "AIの最終推奨",
    "loc.investmentGuide": "初期投資目安",
    "loc.areaRanking": "推奨エリアランキング",
    "loc.estPop": "推定人口",
    "loc.mainTarget": "主要ターゲット",
    "loc.competitionDensity": "競合密度",
    "loc.rentEstimate": "家賃相場",
    "loc.monthlyCustomers": "月間見込み顧客数",
    "loc.strengths": "強み",
    "loc.risks": "リスク",
    "loc.storeTab": "出店",
    "loc.adTab": "広告",
    "loc.flyerTab": "チラシ",
    "loc.compTable": "エリア比較表",
    "loc.area": "エリア",
    "loc.score": "スコア",
    "loc.competition": "競合",
    "loc.targetFit": "ターゲット適合",
    "loc.costEff": "コスト効率",
    "loc.growth": "成長性",
    "loc.actionPlan": "具体的アクションプラン",
    "loc.matchComplete": "エリアマッチング分析が完了しました",
    "loc.matchFailed": "分析に失敗しました",
    "loc.enterIndustry": "業種を入力してください",
    "loc.enterService": "サービス内容を入力してください",
    "loc.points": "点",

    // Media Plan
    "media.badge": "媒体プラン",
    "media.title": "統合媒体プランナー",
    "media.subtitle": "Google広告・Meta広告・チラシ配布を一括でプランニングします。",
    "media.storeLocation": "店舗所在地",
    "media.industry": "業種",
    "media.storeName": "店舗名（任意）",
    "media.monthlyBudget": "月間予算（任意）",
    "media.targetAudience": "ターゲット層（任意）",
    "media.generating": "プラン生成中...",
    "media.generate": "統合媒体プランを作成",
    "media.metaAds": "Meta広告",
    "media.googleAds": "Google広告",
    "media.flyer": "チラシ",
    "media.campaignObj": "キャンペーン目的",
    "media.dailyBudget": "日予算",
    "media.expectedCPM_CTR": "期待CPM / CTR",
    "media.campaignType": "キャンペーンタイプ",
    "media.expectedCTR_CPA": "期待CTR / CPA",
    "media.recKeywords": "推奨キーワード",
    "media.adCopies": "広告文案",
    "media.totalQty": "合計部数",
    "media.totalCost": "合計費用",
    "media.expectedResponse": "期待反応率",
    "media.distAreas": "配布エリア",
    "media.distTiming": "配布タイミング",
    "media.bestDays": "最適な曜日",
    "media.bestTime": "最適な時間帯",
    "media.frequency": "推奨頻度",
    "media.catchcopies": "キャッチコピー案",
    "media.noMetaData": "Meta広告データがありません",
    "media.noGoogleData": "Google広告データがありません",
    "media.noFlyerData": "チラシデータがありません",
    "media.planComplete": "媒体プランが完成しました",
    "media.planFailed": "プラン生成に失敗しました",
    "media.age": "年齢",
    "media.gender": "性別",
    "media.householdCount": "世帯数",
    "media.recQty": "推奨部数",

    // Agency Dashboard
    "agency.badge": "代理店ダッシュボード",
    "agency.title": "案件管理",
    "agency.subtitle": "すべての診断・候補地を一元管理します。",
    "agency.newDiagnosis": "新規診断",
    "agency.addCandidate": "候補地追加",
    "agency.totalCases": "総案件数",
    "agency.completed": "診断完了",
    "agency.processing": "処理中",
    "agency.candidates": "出店候補地",
    "agency.searchPh": "店舗名・業種で検索...",
    "agency.statusAll": "すべて",
    "agency.statusCompleted": "完了",
    "agency.statusProcessing": "処理中",
    "agency.statusDraft": "下書き",
    "agency.colType": "種別",
    "agency.colStore": "店舗名",
    "agency.colIndustry": "業種",
    "agency.colDate": "分析日時",
    "agency.colStatus": "ステータス",
    "agency.colAction": "操作",
    "agency.typeDiagnosis": "診断",
    "agency.typeCandidate": "候補地",
    "agency.details": "詳細",
    "agency.noCases": "該当する案件がありません",

    // Report
    "report.badge": "統合レポート",
    "report.title": "分析レポート",
    "report.subtitle": "商圏分析・推奨施策・広告配分・チラシ出稿案を1ページで確認できます。",
    "report.address": "住所",
    "report.industry": "業種",
    "report.storeName": "店舗名（任意）",
    "report.monthlyBudget": "月間予算（任意）",
    "report.target": "ターゲット（任意）",
    "report.generating": "レポート生成中...",
    "report.generate": "統合レポートを作成",
    "report.areaAnalysis": "商圏分析結果",
    "report.recActions": "推奨施策",
    "report.adBudget": "広告予算配分",
    "report.flyerPlan": "チラシ出稿案",
    "report.areaLabel": "エリア",
    "report.estPop": "推定人口",
    "report.estHouseholds": "推定世帯数",
    "report.mainTarget": "主要ターゲット",
    "report.competitiveEnv": "競合環境",
    "report.monthlyBudgetLabel": "月間予算",
    "report.monthlyTotalBudget": "月間合計予算",
    "report.totalQty": "合計部数",
    "report.totalCost": "合計費用",
    "report.expectedResponse": "期待反応率",
    "report.expectedROI": "期待ROI",
    "report.recQty": "推奨部数",
    "report.targetDesc": "ターゲット",
    "report.reportComplete": "レポートが完成しました",
    "report.reportFailed": "レポート生成に失敗しました",
    "report.runningAI": "3つのAI分析を同時実行中...",
    "report.recommended": "推奨",

    // Store Candidates
    "sc.badge": "出店候補地管理",
    "sc.title": "出店候補地の登録",
    "sc.subtitle": "出店を検討しているエリアを登録し、商圏分析や媒体プランに活用できます。",
    "sc.addNew": "新しい候補地を追加",
    "sc.closeForm": "フォームを閉じる",
    "sc.formTitle": "候補地情報を入力",
    "sc.formDesc": "できるだけ詳しく入力すると、分析精度が向上します。",
    "sc.storeName": "店舗名",
    "sc.industry": "業種",
    "sc.address": "住所",
    "sc.latitude": "緯度（任意）",
    "sc.longitude": "経度（任意）",
    "sc.memo": "出店候補地メモ（任意）",
    "sc.registering": "登録中...",
    "sc.register": "候補地を登録",
    "sc.noData": "候補地がまだありません",
    "sc.noDataDesc": "出店を検討しているエリアを登録しましょう。",
    "sc.addFirst": "最初の候補地を追加",
    "sc.registered": "出店候補地を登録しました",
    "sc.deleted": "候補地を削除しました",
    "sc.fetchError": "データの取得に失敗しました",
    "sc.draft": "下書き",

    // Store Input
    "si.badge": "店舗情報入力",
    "si.title": "店舗の情報を教えてください",
    "si.subtitle": "入力内容をもとに、AIが集客診断と施策を提案します。",
    "si.basicInfo": "基本情報",
    "si.basicInfoDesc": "できるだけ詳しく入力いただくと、より精度の高い診断が可能です。",
    "si.storeName": "店舗名",
    "si.industry": "業種",
    "si.address": "住所",
    "si.station": "最寄駅",
    "si.target": "ターゲット層",
    "si.strengths": "店の強み",
    "si.concerns": "現在の悩み",
    "si.adBudget": "月の広告・販促予算",
    "si.competitors": "競合店舗",
    "si.mediaLabel": "利用したい媒体（複数選択可）",
    "si.submitting": "AIが分析中…（30秒ほどかかります）",
    "si.submit": "診断を開始する",
    "si.aiStarted": "AIが診断を開始しました…",
    "si.diagComplete": "診断が完了しました！",
    "si.diagFailed": "診断の開始に失敗しました",
    "si.enterStoreName": "店舗名を入力してください",
    "si.enterIndustry": "業種を入力してください",
    "si.enterAddress": "住所を入力してください",
    "si.mediaGBP": "Googleビジネスプロフィール",
    "si.mediaIG": "Instagram",
    "si.mediaX": "X（Twitter）",
    "si.mediaLINE": "LINE公式アカウント",
    "si.mediaFlyer": "チラシ・ポスティング",
    "si.mediaWebAd": "Web広告（Google/Meta）",
    "si.mediaPortal": "食べログ・ホットペッパー等",

    // Dashboard subscription
    "dash.subBadge.free": "フリープラン",
    "dash.subBadge.pro": "プロプラン",
    "dash.subBadge.until": "まで",
  },
  en: {
    // Nav & Layout
    "nav.home": "Home",
    "nav.analysis": "Analysis",
    "nav.promotion": "Promotion",
    "nav.management": "Management",
    "nav.diagnosis": "Diagnosis",
    "nav.areaAnalysis": "Trade Area Analysis",
    "nav.locationMatch": "Location Match",
    "nav.storeCandidates": "Store Candidates",
    "nav.mediaPlan": "Integrated Media Plan",
    "nav.adProposal": "Ad Proposal",
    "nav.flyerPlan": "Flyer Planning",
    "nav.agencyDashboard": "Agency Dashboard",
    "nav.report": "Integrated Report",
    "nav.diagnosisList": "Diagnosis List",
    "nav.storeInput": "Store Input (Diagnosis)",
    "nav.logout": "Logout",
    "nav.login": "Login",
    "footer.copyright": "© 2024 MapBoost AI",
    "footer.description": "Local Marketing Analysis Tool — Area Analysis, Store Analysis, Ad Proposals, Flyer Distribution",

    // Index / Hero
    "hero.badge": "Map-Driven Store Marketing AI",
    "hero.title1": "Find the best",
    "hero.title2": "marketing strategy for",
    "hero.title3": "your store in minutes",
    "hero.description": "Simply enter your store info and AI will create a marketing plan based on your trade area, customers, and competitors.",
    "hero.cta": "Start Free Diagnosis",
    "hero.loginBtn": "Login",
    "hero.visitRate": "Visit Rate",
    "hero.awareness": "Awareness",
    "features.badge": "Key Features",
    "features.title": "What MapBoost AI Can Do",
    "features.description": "Enter your store info and get 6 automated analyses and recommendations.",
    "feature.diagnosis.title": "Marketing Diagnosis",
    "feature.diagnosis.desc": "Analyze trade area, customers, and competitors to visualize strengths and weaknesses.",
    "feature.area.title": "Trade Area Analysis",
    "feature.area.desc": "AI analyzes demographics, age distribution, and households within 1-5km radius.",
    "feature.candidates.title": "Store Candidate Management",
    "feature.candidates.desc": "Register and manage potential store locations with trade area scoring.",
    "feature.media.title": "Media Plan",
    "feature.media.desc": "AI recommends optimal budget allocation for Meta, Google, and flyers.",
    "feature.agency.title": "Agency Dashboard",
    "feature.agency.desc": "Manage client and store analysis projects at a glance with status tracking.",
    "feature.report.title": "Integrated Report",
    "feature.report.desc": "Consolidate area analysis, strategies, ads, and flyers into one page. PDF export supported.",
    "steps.title": "4 Easy Steps",
    "steps.description": "From input to execution in just a few minutes.",
    "step1.title": "Enter Store Info",
    "step1.desc": "Input industry, address, strengths, and concerns",
    "step2.title": "AI Analyzes & Suggests",
    "step2.desc": "Get diagnosis results and strategies in seconds",
    "step3.title": "Generate Promo Copy",
    "step3.desc": "Create copy for each channel with one click",
    "step4.title": "Execute & Improve",
    "step4.desc": "Run and refine strategies using KPI tracking",
    "cta.title": "Try a free diagnosis today",
    "cta.description": "Takes about 3 minutes. Start right after signing up.",

    // Auth
    "auth.title": "MapBoost AI",
    "auth.subtitle": "Login or create a new account",
    "auth.loginTab": "Login",
    "auth.signupTab": "Sign Up",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.passwordHint": "Password (6+ characters)",
    "auth.loginBtn": "Login",
    "auth.signupBtn": "Create Account",
    "auth.processing": "Processing…",
    "auth.or": "or",
    "auth.googleLogin": "Login with Google",
    "auth.googleSignup": "Sign up with Google",
    "auth.loginFailed": "Login failed. Please check your email and password.",
    "auth.signupSuccess": "Confirmation email sent. Please check your inbox.",
    "auth.googleFailed": "Google login failed",
    "loading": "Loading...",

    // Store Input
    "store.badge": "Store Information",
    "store.title": "Tell us about your store",
    "store.description": "AI will suggest marketing strategies based on your input.",
    "store.basicInfo": "Basic Information",
    "store.basicInfoDesc": "The more detail you provide, the more accurate the diagnosis.",
    "store.name": "Store Name",
    "store.industry": "Industry",
    "store.address": "Address",
    "store.station": "Nearest Station",
    "store.target": "Target Audience",
    "store.strengths": "Store Strengths",
    "store.concerns": "Current Concerns",
    "store.budget": "Monthly Ad/Promo Budget",
    "store.competitors": "Competitors",
    "store.media": "Channels to Use (select multiple)",
    "store.submit": "Start Diagnosis",
    "store.submitting": "AI is analyzing… (about 30 seconds)",
    "store.aiStarted": "AI diagnosis started…",
    "store.completed": "Diagnosis completed!",
    "store.failed": "Failed to start diagnosis",

    // Diagnosis
    "diag.badge": "Diagnosis Results",
    "diag.title": " Marketing Diagnosis",
    "diag.subtitle": "Recommended strategies based on AI analysis.",
    "diag.notFound": "Diagnosis results not found",
    "diag.generating": "Generating diagnosis results…",
    "diag.backToDashboard": "Back to Dashboard",
    "diag.strengths": "Store Strengths",
    "diag.weaknesses": "Weaknesses / Issues",
    "diag.targetCustomers": "Target Customer Segments",
    "diag.differentiation": "Differentiation Points",
    "diag.bottlenecks": "Marketing Bottlenecks",
    "diag.bottlenecksDesc": "Key factors hindering customer acquisition",
    "diag.actions": "Actions to Take Now",
    "diag.estimatedCost": "Est. Cost",
    "diag.difficulty": "Difficulty",
    "diag.expectedEffect": "Expected Effect",
    "diag.pdfExport": "Export PDF",
    "diag.viewPromo": "View Promo Copy",
    "diag.viewKpi": "View KPI Plan",

    // PromoText
    "promo.title": "Auto-Generated Promo Copy",
    "promo.subtitle": "— Promo copy by channel",
    "promo.generating": "Generating promo copy…",
    "promo.dataNotFound": "Data not found",
    "promo.copy": "Copy",
    "promo.copied": "Copied to clipboard",
    "promo.softer": "Softer",
    "promo.stronger": "Stronger",
    "promo.alternative": "Alternative",
    "promo.regenerate": "Regenerate Promo Copy",
    "promo.regenerated": "Promo copy regenerated",
    "promo.regenerateFailed": "Regeneration failed",
    "promo.adjustedSoft": "Adjusted to softer tone",
    "promo.adjustedStrong": "Adjusted to stronger tone",
    "promo.adjustedAlt": "Alternative generated",
    "promo.adjustFailed": "Adjustment failed",

    // KPI
    "kpi.badge": "KPI Design",
    "kpi.title": " KPI Design",
    "kpi.subtitle": "Metrics and targets to measure strategy effectiveness",
    "kpi.generating": "Generating KPI design…",
    "kpi.target": "Target",
    "kpi.measurement": "Measurement",
    "kpi.frequency": "Review Frequency",

    // Dashboard
    "dash.badge": "Dashboard",
    "dash.title": "Diagnosis Management",
    "dash.subtitle": "Review and manage past diagnosis reports.",
    "dash.newDiagnosis": "Create New Diagnosis",
    "dash.noDiagnosis": "No diagnoses yet",
    "dash.noDiagnosisDesc": "Enter your store info to start an AI-powered marketing diagnosis.",
    "dash.createFirst": "Create First Diagnosis",
    "dash.totalDiagnoses": "Total Diagnoses",
    "dash.completed": "Completed",
    "dash.thisMonth": "This Month",
    "dash.latest": "Latest",
    "dash.trendTitle": "Diagnosis Trend (Last 6 Months)",
    "dash.noTrendData": "No diagnosis data yet",
    "dash.totalCount": "Total",
    "dash.completedCount": "Completed",
    "dash.report": "Report",
    "dash.promoText": "Promo Copy",
    "dash.status.completed": "Done",
    "dash.status.processing": "Processing",
    "dash.status.pending": "Creating",
    "dash.status.error": "Error",
    "dash.strengthsCount": "Strengths",
    "dash.actionsCount": "Actions",
    "dash.createdOn": " created",

    // Area Analysis
    "area.badge": "Area Analysis",
    "area.title": "Trade Area & Store Analysis",
    "area.subtitle": "Enter an address and let AI analyze demographics and market potential.",
    "area.tabArea": "Trade Area",
    "area.tabOpening": "Store Opening",
    "area.addressLabel": "Address / Area Name",
    "area.radiusLabel": "Trade Area Radius",
    "area.industryLabel": "Industry",
    "area.industryOptional": " (optional)",
    "area.analyze": "Analyze with AI",
    "area.analyzing": "Analyzing...",
    "area.pdfDownload": "Download PDF",
    "area.realData": "Real Data",
    "area.aiEstimate": "AI Estimate",
    "area.censusTitle": "Census Data",
    "area.totalPopulation": "Total Population",
    "area.totalHouseholds": "Households",
    "area.dataSource": "Data Source",
    "area.ageComposition": "Age Distribution (Real Data)",
    "area.areaLabel": "Area",
    "area.estPopulation": "Est. Population",
    "area.estHouseholds": "Est. Households",
    "area.radius": "Radius",
    "area.characteristics": "Area Characteristics",
    "area.primaryTarget": "Primary Target",
    "area.ageDistribution": "Age Distribution",
    "area.householdComposition": "Household Types",
    "area.suitableIndustries": "Suitable Industries",
    "area.unsuitableIndustries": "Unsuitable Industries",
    "area.visitMotivations": "Visit Motivations",
    "area.competitiveEnv": "Competitive Environment",
    "area.scoreBreakdown": "Score Breakdown",
    "area.successProb": "Success Probability",
    "area.targetCustomer": "Target Customer",
    "area.unitPrice": "Est. Unit Price",
    "area.visitFreq": "Est. Visit Frequency",
    "area.riskFactors": "Risk Factors",
    "area.improvements": "Improvement Advice",
    "area.risk": "Risk",
    "area.countermeasure": "Mitigation",
    "area.analysisComplete": "Analysis complete (AI estimate)",
    "area.censusAnalysisComplete": "Analysis complete based on census data",
    "area.analysisFailed": "Analysis failed",
    "area.enterAddress": "Please enter an address",
    "area.enterIndustry": "Please enter an industry",
    "area.population": "Population",
    "area.proportion": "Proportion",
    "area.radius1km": "1km Radius",
    "area.radius3km": "3km Radius",
    "area.radius5km": "5km Radius",

    // Flyer Plan
    "flyer.badge": "Flyer Distribution",
    "flyer.title": "Flyer Distribution Planner",
    "flyer.subtitle": "AI designs optimal distribution areas, quantities, and catchphrases.",
    "flyer.storeLocation": "Store Location",
    "flyer.industry": "Industry",
    "flyer.storeName": "Store Name (optional)",
    "flyer.budget": "Budget Estimate (optional)",
    "flyer.target": "Target Audience (optional)",
    "flyer.generate": "Create Distribution Plan with AI",
    "flyer.generating": "Generating plan...",
    "flyer.pdfDownload": "Download PDF",
    "flyer.summary": "Distribution Plan Overview",
    "flyer.totalQuantity": "Total Quantity",
    "flyer.totalCost": "Total Cost",
    "flyer.expectedResponse": "Expected Response Rate",
    "flyer.expectedROI": "Expected ROI",
    "flyer.distributionPlan": "Distribution Area Plan",
    "flyer.priority": "Priority",
    "flyer.estHouseholds": "Est. Households",
    "flyer.targetDesc": "Target",
    "flyer.areaDistribution": "Distribution by Area",
    "flyer.costBreakdown": "Cost Breakdown",
    "flyer.printUnit": "Print Unit Cost",
    "flyer.distUnit": "Dist. Unit Cost",
    "flyer.printTotal": "Total Print Cost",
    "flyer.distTotal": "Total Dist. Cost",
    "flyer.total": "Total",
    "flyer.timing": "Distribution Timing",
    "flyer.bestDays": "Best Days",
    "flyer.bestTimeSlots": "Best Time Slots",
    "flyer.frequency": "Recommended Frequency",
    "flyer.seasonalAdvice": "Seasonal Advice",
    "flyer.catchcopies": "Catchphrase Ideas",
    "flyer.designTips": "Design Advice",
    "flyer.completed": "Flyer distribution plan completed",
    "flyer.failed": "Failed to generate plan",
    "flyer.copied": "Copied",
    "flyer.quantity": "Quantity",
    "flyer.households": "Households",

    // Ad Proposal
    "ad.badge": "Ad Proposal",
    "ad.title": "Ad Planner",
    "ad.subtitle": "AI designs optimal plans for Google Ads and Meta Ads.",
    "ad.storeLocation": "Store Location",
    "ad.industry": "Industry",
    "ad.storeName": "Store Name (optional)",
    "ad.budget": "Monthly Ad Budget (optional)",
    "ad.target": "Target Audience (optional)",
    "ad.generate": "Create Ad Proposal with AI",
    "ad.generating": "Generating proposal...",
    "ad.pdfDownload": "Download PDF",
    "ad.strategySummary": "Ad Strategy Overview",
    "ad.recommendedPlatform": "Recommended Platform",
    "ad.monthlyBudget": "Monthly Total Budget",
    "ad.expectedROAS": "Expected ROAS",
    "ad.campaignType": "Campaign Type",
    "ad.dailyBudget": "Daily Budget",
    "ad.expectedCTR": "Expected CTR",
    "ad.keywords": "Recommended Keywords",
    "ad.adCopies": "Ad Copy",
    "ad.campaignObjective": "Campaign Objective",
    "ad.expectedCPM_CTR": "Expected CPM / CTR",
    "ad.targetAudience": "Target Audience",
    "ad.adCreatives": "Ad Creative Ideas",
    "ad.strategyTips": "Overall Strategy & Tips",
    "ad.recommend": "Recommended",
    "ad.completed": "Ad proposal completed",
    "ad.failed": "Failed to generate proposal",
    "ad.copied": "Copied",

    // Location Match
    "loc.badge": "Area Matching",
    "loc.title": "Location Matching",
    "loc.subtitle": "AI suggests the best areas for your store, ads, and flyer distribution.",
    "loc.industry": "Industry",
    "loc.budgetScale": "Budget Scale (optional)",
    "loc.preferredArea": "Preferred Area / Current Location (optional)",
    "loc.target": "Target Audience (optional)",
    "loc.serviceDesc": "Service Description",
    "loc.otherPrefs": "Other Preferences (optional)",
    "loc.generate": "Run AI Area Matching",
    "loc.generating": "Analyzing areas...",
    "loc.pdfDownload": "Download PDF",
    "loc.analysisSummary": "Analysis Summary",
    "loc.aiRecommendation": "AI's Top Recommendation",
    "loc.initialInvestment": "Est. Initial Investment",
    "loc.areaRanking": "Recommended Area Ranking",
    "loc.estPopulation": "Est. Population",
    "loc.mainTarget": "Main Target",
    "loc.competitionLevel": "Competition Level",
    "loc.rentEstimate": "Rent Estimate",
    "loc.monthlyCustomers": "Est. Monthly Customers",
    "loc.strengths": "Strengths",
    "loc.risks": "Risks",
    "loc.storeTab": "Store",
    "loc.adTab": "Ads",
    "loc.flyerTab": "Flyers",
    "loc.comparisonTable": "Area Comparison Table",
    "loc.area": "Area",
    "loc.score": "Score",
    "loc.competition": "Competition",
    "loc.targetFit": "Target Fit",
    "loc.costEfficiency": "Cost Efficiency",
    "loc.growthPotential": "Growth Potential",
    "loc.actionPlan": "Action Plan",
    "loc.completed": "Area matching analysis completed",
    "loc.failed": "Analysis failed",
    "loc.enterIndustry": "Please enter an industry",
    "loc.enterService": "Please enter service description",

    // Media Plan
    "media.badge": "Media Plan",
    "media.title": "Integrated Media Planner",
    "media.subtitle": "Plan Google Ads, Meta Ads, and flyer distribution all at once.",
    "media.storeLocation": "Store Location",
    "media.industry": "Industry",
    "media.storeName": "Store Name (optional)",
    "media.budget": "Monthly Budget (optional)",
    "media.target": "Target Audience (optional)",
    "media.generate": "Create Integrated Media Plan",
    "media.generating": "Generating plan...",
    "media.pdfDownload": "Download PDF",
    "media.noMetaData": "No Meta Ads data",
    "media.noGoogleData": "No Google Ads data",
    "media.noFlyerData": "No flyer data",
    "media.completed": "Media plan completed",
    "media.failed": "Failed to generate plan",
    "media.distributionArea": "Distribution Areas",
    "media.distributionTiming": "Distribution Timing",
    "media.catchcopies": "Catchphrase Ideas",

    // Agency Dashboard
    "agency.badge": "Agency Dashboard",
    "agency.title": "Project Management",
    "agency.subtitle": "Manage all diagnoses and store candidates in one place.",
    "agency.newDiagnosis": "New Diagnosis",
    "agency.addCandidate": "Add Candidate",
    "agency.totalProjects": "Total Projects",
    "agency.diagCompleted": "Completed",
    "agency.processing": "Processing",
    "agency.storeCandidates": "Store Candidates",
    "agency.searchPlaceholder": "Search by store name or industry...",
    "agency.statusFilter": "Status",
    "agency.all": "All",
    "agency.completed": "Completed",
    "agency.pending": "Processing",
    "agency.draft": "Draft",
    "agency.noResults": "No matching projects found",
    "agency.type": "Type",
    "agency.storeName": "Store Name",
    "agency.industry": "Industry",
    "agency.date": "Analysis Date",
    "agency.status": "Status",
    "agency.action": "Action",
    "agency.details": "Details",
    "agency.typeDiagnosis": "Diagnosis",
    "agency.typeCandidate": "Candidate",

    // Report
    "report.badge": "Integrated Report",
    "report.title": "Analysis Report",
    "report.subtitle": "View trade area analysis, strategies, ad allocation, and flyer plans on one page.",
    "report.address": "Address",
    "report.industry": "Industry",
    "report.storeName": "Store Name (optional)",
    "report.budget": "Monthly Budget (optional)",
    "report.target": "Target (optional)",
    "report.generate": "Create Integrated Report",
    "report.generating": "Generating report...",
    "report.pdfDownload": "Download PDF",
    "report.failed": "Report generation failed",
    "report.aiRunning": "Running 3 AI analyses simultaneously...",
    "report.tradeArea": "Trade Area Analysis",
    "report.recommendations": "Recommended Strategies",
    "report.adBudget": "Ad Budget Allocation",
    "report.flyerPlan": "Flyer Distribution Plan",
    "report.completed": "Report completed",
    "report.area": "Area",
    "report.estPopulation": "Est. Population",
    "report.estHouseholds": "Est. Households",
    "report.mainTarget": "Main Target",
    "report.competitiveEnv": "Competitive Environment",
    "report.monthlyBudget": "Monthly Budget",
    "report.monthlyTotal": "Monthly Total Budget",

    // Store Candidates
    "cand.badge": "Store Candidates",
    "cand.title": "Store Candidate Registration",
    "cand.subtitle": "Register areas you're considering for new stores and use them for analysis.",
    "cand.addNew": "Add New Candidate",
    "cand.closeForm": "Close Form",
    "cand.formTitle": "Enter Candidate Information",
    "cand.formDesc": "More detail leads to better analysis accuracy.",
    "cand.storeName": "Store Name",
    "cand.industry": "Industry",
    "cand.address": "Address",
    "cand.latitude": "Latitude (optional)",
    "cand.longitude": "Longitude (optional)",
    "cand.memo": "Notes (optional)",
    "cand.register": "Register Candidate",
    "cand.registering": "Registering...",
    "cand.registered": "Store candidate registered",
    "cand.deleted": "Candidate deleted",
    "cand.fetchFailed": "Failed to fetch data",
    "cand.empty": "No candidates yet",
    "cand.emptyDesc": "Register areas you're considering for new stores.",
    "cand.addFirst": "Add First Candidate",

    // NotFound
    "notFound.title": "Page not found",
    "notFound.back": "Return to Home",

    // Common
    "common.required": "required",
    "common.optional": "optional",
    "common.enterAddress": "Please enter an address",
    "common.enterIndustry": "Please enter an industry",
    "common.copied": "Copied",

    // Pricing
    "pricing.badge": "Plans & Pricing",
    "pricing.title": "Choose Your Plan",
    "pricing.subtitle": "Start free and upgrade when you need more.",
    "pricing.month": "month",
    "pricing.currentPlan": "Current Plan",
    "pricing.upgrade": "Upgrade to Pro",
    "pricing.manage": "Manage Subscription",
    "pricing.error": "An error occurred. Please try again.",
    "pricing.free.name": "Free",
    "pricing.free.desc": "Try core features for free",
    "pricing.free.f1": "Up to 3 diagnoses per month",
    "pricing.free.f2": "Basic area analysis",
    "pricing.free.f3": "Promo text generation",
    "pricing.free.f4": "PDF export",
    "pricing.pro.name": "Pro",
    "pricing.pro.desc": "Unlimited access for serious store owners",
    "pricing.pro.f1": "Unlimited diagnoses & analyses",
    "pricing.pro.f2": "Advanced area analysis with census data",
    "pricing.pro.f3": "Flyer plan design",
    "pricing.pro.f4": "Ad proposal generation",
    "pricing.pro.f5": "Integrated media plan",
    "pricing.pro.f6": "Priority support",
    "nav.pricing": "Plans",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("app-language");
    return (saved === "en" || saved === "ja") ? saved : "ja";
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("app-language", lang);
  }, []);

  const t = useCallback((key: string): string => {
    return translations[language][key] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
