import { createContext, useContext, useState, useCallback, ReactNode } from "react";

export type Language = "ja" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  ja: {
    // Nav & Layout
    "nav.home": "トップ",
    "nav.analysis": "分析",
    "nav.promotion": "販促",
    "nav.management": "管理",
    "nav.diagnosis": "診断",
    "nav.areaAnalysis": "商圏・出店分析",
    "nav.locationMatch": "エリア適性",
    "nav.storeCandidates": "出店候補地管理",
    "nav.mediaPlan": "統合媒体プラン",
    "nav.adProposal": "広告提案",
    "nav.flyerPlan": "チラシ設計",
    "nav.agencyDashboard": "案件管理",
    "nav.report": "統合レポート",
    "nav.diagnosisList": "診断一覧",
    "nav.storeInput": "店舗入力（診断）",
    "nav.logout": "ログアウト",
    "nav.login": "ログイン",
    "footer.copyright": "© 2026 MapBoost AI",
    "footer.description": "ローカルマーケティング分析ツール — 地域分析・出店分析・広告提案・チラシ配布設計",

    // Index / Hero
    "hero.badge": "マップ連動型 店舗集客AI",
    "hero.title1": "あなたのお店に合う",
    "hero.title2": "集客施策を、",
    "hero.title3": "数分で提案",
    "hero.description": "店舗情報を入力するだけで、商圏・客層・競合をふまえた集客プランをAIが作成します。",
    "hero.cta": "無料で診断する",
    "hero.loginBtn": "ログイン",
    "hero.visitRate": "来店率",
    "hero.awareness": "認知度",
    "features.badge": "主な機能",
    "features.title": "MapBoost AI でできること",
    "features.description": "店舗情報を入力するだけで、6つの分析・提案を自動で行います。",
    "feature.diagnosis.title": "集客診断",
    "feature.diagnosis.desc": "商圏・客層・競合を分析し、店舗の強み・弱みを可視化します。",
    "feature.area.title": "商圏分析",
    "feature.area.desc": "半径1〜5kmの人口統計・年齢構成・世帯構成をAIが分析。",
    "feature.candidates.title": "出店候補地管理",
    "feature.candidates.desc": "出店候補地を登録・管理し、商圏スコアで比較評価できます。",
    "feature.media.title": "媒体プラン",
    "feature.media.desc": "Meta・Google・チラシの最適な予算配分とターゲットをAIが提案。",
    "feature.agency.title": "案件管理ダッシュボード",
    "feature.agency.desc": "クライアント・店舗の分析案件を一覧で管理。ステータスも一目瞭然。",
    "feature.report.title": "統合レポート",
    "feature.report.desc": "商圏分析・施策・広告・チラシを1ページに集約。PDF出力も対応。",
    "steps.title": "かんたん4ステップ",
    "steps.description": "入力から施策実行まで、わずか数分で完了します。",
    "step1.title": "店舗情報を入力",
    "step1.desc": "業種・住所・強み・悩みなどを入力",
    "step2.title": "AIが分析・提案",
    "step2.desc": "数秒で診断結果と施策を表示",
    "step3.title": "販促文を生成",
    "step3.desc": "各媒体向けの文面をワンクリック作成",
    "step4.title": "実行 & 改善",
    "step4.desc": "KPIを見ながら施策を実行・改善",
    "cta.title": "まずは無料で診断してみましょう",
    "cta.description": "所要時間は約3分。登録後すぐに始められます。",

    // Auth
    "auth.title": "MapBoost AI",
    "auth.subtitle": "アカウントにログインまたは新規登録",
    "auth.loginTab": "ログイン",
    "auth.signupTab": "新規登録",
    "auth.email": "メールアドレス",
    "auth.password": "パスワード",
    "auth.passwordHint": "パスワード（6文字以上）",
    "auth.loginBtn": "ログイン",
    "auth.signupBtn": "アカウント作成",
    "auth.processing": "処理中…",
    "auth.or": "または",
    "auth.googleLogin": "Googleでログイン",
    "auth.googleSignup": "Googleでアカウント作成",
    "auth.loginFailed": "ログインに失敗しました。メールアドレスとパスワードをご確認ください。",
    "auth.signupSuccess": "確認メールを送信しました。メールをご確認ください。",
    "auth.googleFailed": "Googleログインに失敗しました",
    "loading": "読み込み中...",

    // Store Input
    "store.badge": "店舗情報入力",
    "store.title": "店舗の情報を教えてください",
    "store.description": "入力内容をもとに、AIが集客診断と施策を提案します。",
    "store.basicInfo": "基本情報",
    "store.basicInfoDesc": "できるだけ詳しく入力いただくと、より精度の高い診断が可能です。",
    "store.name": "店舗名",
    "store.industry": "業種",
    "store.address": "住所",
    "store.station": "最寄駅",
    "store.target": "ターゲット層",
    "store.strengths": "店の強み",
    "store.concerns": "現在の悩み",
    "store.budget": "月の広告・販促予算",
    "store.competitors": "競合店舗",
    "store.media": "利用したい媒体（複数選択可）",
    "store.submit": "診断を開始する",
    "store.submitting": "AIが分析中…（30秒ほどかかります）",
    "store.aiStarted": "AIが診断を開始しました…",
    "store.completed": "診断が完了しました！",
    "store.failed": "診断の開始に失敗しました",

    // Diagnosis
    "diag.badge": "診断結果",
    "diag.title": "の集客診断",
    "diag.subtitle": "AIが分析した結果をもとに、最適な施策を提案します。",
    "diag.notFound": "診断結果が見つかりませんでした",
    "diag.generating": "診断結果を生成中です…",
    "diag.backToDashboard": "ダッシュボードに戻る",
    "diag.strengths": "店舗の強み",
    "diag.weaknesses": "弱み・課題",
    "diag.targetCustomers": "狙うべき客層",
    "diag.differentiation": "差別化ポイント",
    "diag.bottlenecks": "集客ボトルネック",
    "diag.bottlenecksDesc": "現在の集客を妨げている主な要因",
    "diag.actions": "今すぐやるべき施策",
    "diag.estimatedCost": "概算コスト",
    "diag.difficulty": "難易度",
    "diag.expectedEffect": "効果の目安",
    "diag.pdfExport": "PDF出力",
    "diag.viewPromo": "販促文を見る",
    "diag.viewKpi": "KPI設計を見る",

    // PromoText
    "promo.title": "販促文の自動生成",
    "promo.subtitle": "— 媒体ごとの販促文",
    "promo.generating": "販促文を生成中です…",
    "promo.dataNotFound": "データが見つかりません",
    "promo.copy": "コピー",
    "promo.copied": "クリップボードにコピーしました",
    "promo.softer": "やわらかく",
    "promo.stronger": "力強く",
    "promo.alternative": "別案を出す",
    "promo.regenerate": "販促文を再生成",
    "promo.regenerated": "販促文を再生成しました",
    "promo.regenerateFailed": "再生成に失敗しました",
    "promo.adjustedSoft": "やわらかく調整しました",
    "promo.adjustedStrong": "力強く調整しました",
    "promo.adjustedAlt": "別案調整しました",
    "promo.adjustFailed": "調整に失敗しました",
    "promo.tabGBP": "Googleビジネスプロフィール",
    "promo.tabIG": "Instagram",
    "promo.tabX": "X",
    "promo.tabFlyer": "チラシ",
    "promo.tabLINE": "LINE",
    "promo.tabAdHeadline": "広告見出し",

    // KPI
    "kpi.badge": "KPI設計",
    "kpi.title": "のKPI設計",
    "kpi.subtitle": "施策の効果を測定するための指標と目標値",
    "kpi.generating": "KPI設計を生成中です…",
    "kpi.target": "目標値",
    "kpi.measurement": "測定方法",
    "kpi.frequency": "確認頻度",

    // Dashboard
    "dash.badge": "ダッシュボード",
    "dash.title": "診断案件の管理",
    "dash.subtitle": "過去の診断レポートの確認・管理ができます。",
    "dash.newDiagnosis": "新しい診断を作成",
    "dash.noDiagnosis": "診断がまだありません",
    "dash.noDiagnosisDesc": "店舗情報を入力して、AIによる集客診断を始めましょう。",
    "dash.createFirst": "最初の診断を作成",
    "dash.totalDiagnoses": "総診断数",
    "dash.completed": "完了済み",
    "dash.thisMonth": "今月の診断",
    "dash.latest": "直近の診断",
    "dash.trendTitle": "診断推移（直近6ヶ月）",
    "dash.noTrendData": "診断データがまだありません",
    "dash.totalCount": "総診断数",
    "dash.completedCount": "完了済み",
    "dash.report": "レポート",
    "dash.promoText": "販促文",
    "dash.status.completed": "完了",
    "dash.status.processing": "処理中",
    "dash.status.pending": "作成中",
    "dash.status.error": "エラー",
    "dash.strengthsCount": "強み",
    "dash.actionsCount": "施策",
    "dash.createdOn": "に作成",

    // Common
    "common.required": "必須",
    "common.optional": "任意",
    "common.enterAddress": "住所を入力してください",
    "common.enterIndustry": "業種を入力してください",
    "common.copied": "コピーしました",

    // NotFound
    "notFound.title": "ページが見つかりません",
    "notFound.back": "ホームに戻る",

    // Pricing
    "pricing.badge": "料金プラン",
    "pricing.title": "プランを選択",
    "pricing.subtitle": "無料で始めて、必要に応じてアップグレードできます。",
    "pricing.month": "月",
    "pricing.currentPlan": "現在のプラン",
    "pricing.upgrade": "Proにアップグレード",
    "pricing.manage": "サブスクリプション管理",
    "pricing.error": "エラーが発生しました。もう一度お試しください。",
    "pricing.free.name": "フリー",
    "pricing.free.desc": "主要機能を無料でお試し",
    "pricing.free.f1": "月3回までの診断",
    "pricing.free.f2": "基本的な商圏分析",
    "pricing.free.f3": "販促テキスト生成",
    "pricing.free.f4": "PDFエクスポート",
    "pricing.pro.name": "プロ",
    "pricing.pro.desc": "本格運用に最適な無制限プラン",
    "pricing.pro.f1": "無制限の診断・分析",
    "pricing.pro.f2": "国勢調査データ連携の商圏分析",
    "pricing.pro.f3": "チラシ設計",
    "pricing.pro.f4": "広告提案の自動生成",
    "pricing.pro.f5": "統合媒体プラン",
    "pricing.pro.f6": "優先サポート",
    "nav.pricing": "料金プラン",

    // Area Analysis
    "area.badge": "地域分析",
    "area.title": "商圏・出店分析",
    "area.subtitle": "住所を入力して、AIが地域の人口統計・市場性を分析します。",
    "area.tabArea": "商圏分析",
    "area.tabOpening": "出店分析",
    "area.address": "住所・エリア名",
    "area.addressPh": "例: 東京都渋谷区神南1丁目",
    "area.radius": "商圏半径",
    "area.industry": "業種",
    "area.industryOptional": "（任意）",
    "area.industryPh": "例: カフェ、学習塾、美容院",
    "area.analyzing": "分析中...",
    "area.analyze": "AIで分析する",
    "area.pdfDownload": "PDFダウンロード",
    "area.realData": "実データ",
    "area.aiEstimate": "AI推定値",
    "area.censusTitle": "国勢調査データ",
    "area.source": "出典",
    "area.areaCode": "地域コード",
    "area.totalPop": "総人口",
    "area.households": "世帯数",
    "area.dataSource": "データソース",
    "area.ageComp": "年齢構成",
    "area.ageCompReal": "年齢構成（実データ）",
    "area.areaLabel": "エリア",
    "area.estPop": "推定人口",
    "area.estHouseholds": "推定世帯数",
    "area.radiusLabel": "商圏半径",
    "area.areaFeatures": "エリアの特徴",
    "area.mainTarget": "主要ターゲット",
    "area.householdComp": "世帯構成",
    "area.suitableInd": "向いている業種",
    "area.unsuitableInd": "不利な業種",
    "area.visitMotivations": "来店動機の傾向",
    "area.competition": "競合環境",
    "area.successProb": "成功確率",
    "area.scoreBreakdown": "スコア内訳",
    "area.targetCustomer": "想定ターゲット",
    "area.unitPrice": "想定客単価",
    "area.visitFreq": "想定来店頻度",
    "area.riskFactors": "リスク要因",
    "area.improvements": "改善アドバイス",
    "area.risk": "リスク",
    "area.countermeasure": "対策",
    "area.enterAddress": "住所を入力してください",
    "area.enterIndustry": "業種を入力してください",
    "area.analysisComplete": "分析が完了しました",
    "area.analysisCompleteReal": "国勢調査データを基に分析が完了しました",
    "area.analysisCompleteFallback": "分析が完了しました（AI推定値）",
    "area.analysisFailed": "分析に失敗しました",
    "area.radius1km": "半径1km",
    "area.radius3km": "半径3km",
    "area.radius5km": "半径5km",
    "area.people": "人",
    "area.householdsUnit": "世帯",
    "area.population": "人口",
    "area.percentage": "割合",

    // Flyer Plan
    "flyer.badge": "チラシ配布設計",
    "flyer.title": "チラシ配布プランナー",
    "flyer.subtitle": "AIが最適な配布エリア・部数・キャッチコピーを自動設計します。",
    "flyer.storeLocation": "店舗所在地",
    "flyer.industry": "業種",
    "flyer.storeName": "店舗名（任意）",
    "flyer.budget": "予算目安（任意）",
    "flyer.targetAudience": "ターゲット層（任意）",
    "flyer.generating": "計画生成中...",
    "flyer.generate": "AIで配布計画を作成",
    "flyer.summary": "配布計画の概要",
    "flyer.totalQty": "合計部数",
    "flyer.totalCost": "合計費用",
    "flyer.expectedResponse": "期待反応率",
    "flyer.expectedROI": "期待ROI",
    "flyer.distAreas": "配布エリア計画",
    "flyer.priority": "優先度",
    "flyer.estHouseholds": "推定世帯",
    "flyer.targetDesc": "ターゲット",
    "flyer.areaDistChart": "エリア別配布部数",
    "flyer.costBreakdown": "費用内訳",
    "flyer.printUnit": "印刷単価",
    "flyer.distUnit": "配布単価",
    "flyer.printTotal": "印刷費合計",
    "flyer.distTotal": "配布費合計",
    "flyer.total": "合計",
    "flyer.timing": "配布タイミング",
    "flyer.bestDays": "最適な曜日",
    "flyer.bestTime": "最適な時間帯",
    "flyer.frequency": "推奨頻度",
    "flyer.seasonalTips": "季節アドバイス",
    "flyer.catchcopies": "キャッチコピー案",
    "flyer.designTips": "デザインアドバイス",
    "flyer.copies": "部",
    "flyer.perSheet": "/枚",
    "flyer.planComplete": "チラシ配布計画が完成しました",
    "flyer.planFailed": "計画の生成に失敗しました",
    "flyer.addressPh": "例: 東京都渋谷区神南1丁目",
    "flyer.industryPh": "例: 美容院、学習塾、居酒屋",
    "flyer.storeNamePh": "例: ヘアサロン BLOOM",
    "flyer.budgetPh": "例: 5万円、10万円",
    "flyer.targetPh": "例: 30〜40代の子育て世帯、近隣のオフィスワーカー",
    "flyer.pdfDownload": "PDFダウンロード",

    // Ad Proposal
    "ad.badge": "広告提案",
    "ad.title": "広告プランナー",
    "ad.subtitle": "AIがGoogle広告・Meta広告の最適プランを自動設計します。",
    "ad.storeLocation": "店舗所在地",
    "ad.industry": "業種",
    "ad.storeName": "店舗名（任意）",
    "ad.monthlyBudget": "月間広告予算（任意）",
    "ad.targetAudience": "ターゲット層（任意）",
    "ad.generating": "提案生成中...",
    "ad.generate": "AIで広告提案を作成",
    "ad.strategySummary": "広告戦略の概要",
    "ad.recPlatform": "推奨プラットフォーム",
    "ad.monthlyTotal": "月間合計予算",
    "ad.expectedROAS": "期待ROAS",
    "ad.googleCPA": "Google CPA",
    "ad.googleAds": "Google 広告",
    "ad.metaAds": "Meta 広告",
    "ad.campaignType": "キャンペーンタイプ",
    "ad.dailyBudget": "日予算",
    "ad.expectedCTR": "期待CTR",
    "ad.recKeywords": "推奨キーワード",
    "ad.adCopies": "広告文案",
    "ad.campaignObj": "キャンペーン目的",
    "ad.expectedCPM_CTR": "期待CPM / CTR",
    "ad.targetAudiences": "ターゲットオーディエンス",
    "ad.age": "年齢",
    "ad.gender": "性別",
    "ad.adCreatives": "広告クリエイティブ案",
    "ad.overallStrategy": "総合戦略・運用Tips",
    "ad.recommended": "推奨",
    "ad.proposalComplete": "広告提案が完成しました",
    "ad.proposalFailed": "提案の生成に失敗しました",
    "ad.addressPh": "例: 東京都渋谷区神南1丁目",
    "ad.industryPh": "例: 美容院、学習塾、居酒屋",
    "ad.storeNamePh": "例: ヘアサロン BLOOM",
    "ad.budgetPh": "例: 5万円、10万円",
    "ad.targetPh": "例: 30〜40代の子育て世帯、近隣のオフィスワーカー",
    "ad.pdfDownload": "PDFダウンロード",

    // Location Match
    "loc.badge": "エリアマッチング",
    "loc.title": "ロケーションマッチング",
    "loc.subtitle": "あなたのサービスに最適な出店・広告・チラシ配布エリアをAIが提案します。",
    "loc.industry": "業種",
    "loc.budgetScale": "予算規模（任意）",
    "loc.preferredArea": "希望エリア・現在地（任意）",
    "loc.targetAudience": "ターゲット層（任意）",
    "loc.serviceDesc": "サービス内容",
    "loc.otherConditions": "その他の条件（任意）",
    "loc.analyzing": "エリア分析中...",
    "loc.analyze": "AIでエリアマッチング",
    "loc.analysisSummary": "分析結果の概要",
    "loc.aiFinalRec": "AIの最終推奨",
    "loc.investmentGuide": "初期投資目安",
    "loc.areaRanking": "推奨エリアランキング",
    "loc.estPop": "推定人口",
    "loc.mainTarget": "主要ターゲット",
    "loc.competitionDensity": "競合密度",
    "loc.rentEstimate": "家賃相場",
    "loc.monthlyCustomers": "月間見込み顧客数",
    "loc.strengths": "強み",
    "loc.risks": "リスク",
    "loc.storeTab": "出店",
    "loc.adTab": "広告",
    "loc.flyerTab": "チラシ",
    "loc.compTable": "エリア比較表",
    "loc.area": "エリア",
    "loc.score": "スコア",
    "loc.competition": "競合密度",
    "loc.targetFit": "ターゲット適合",
    "loc.costEff": "コスト効率",
    "loc.growth": "成長性",
    "loc.actionPlan": "具体的アクションプラン",
    "loc.matchComplete": "エリアマッチング分析が完了しました",
    "loc.matchFailed": "分析に失敗しました",
    "loc.enterIndustry": "業種を入力してください",
    "loc.enterService": "サービス内容を入力してください",
    "loc.points": "点",

    // Media Plan
    "media.badge": "媒体プラン",
    "media.title": "統合媒体プランナー",
    "media.subtitle": "Google広告・Meta広告・チラシ配布を一括でプランニングします。",
    "media.storeLocation": "店舗所在地",
    "media.industry": "業種",
    "media.storeName": "店舗名（任意）",
    "media.monthlyBudget": "月間予算（任意）",
    "media.targetAudience": "ターゲット層（任意）",
    "media.generating": "プラン生成中...",
    "media.generate": "統合媒体プランを作成",
    "media.metaAds": "Meta広告",
    "media.googleAds": "Google広告",
    "media.flyer": "チラシ",
    "media.campaignObj": "キャンペーン目的",
    "media.dailyBudget": "日予算",
    "media.expectedCPM_CTR": "期待CPM / CTR",
    "media.campaignType": "キャンペーンタイプ",
    "media.expectedCTR_CPA": "期待CTR / CPA",
    "media.recKeywords": "推奨キーワード",
    "media.adCopies": "広告文案",
    "media.totalQty": "合計部数",
    "media.totalCost": "合計費用",
    "media.expectedResponse": "期待反応率",
    "media.distAreas": "配布エリア",
    "media.distTiming": "配布タイミング",
    "media.bestDays": "最適な曜日",
    "media.bestTime": "最適な時間帯",
    "media.frequency": "推奨頻度",
    "media.catchcopies": "キャッチコピー案",
    "media.noMetaData": "Meta広告データがありません",
    "media.noGoogleData": "Google広告データがありません",
    "media.noFlyerData": "チラシデータがありません",
    "media.planComplete": "媒体プランが完成しました",
    "media.planFailed": "プラン生成に失敗しました",
    "media.age": "年齢",
    "media.gender": "性別",
    "media.householdCount": "世帯数",
    "media.recQty": "推奨部数",

    // Agency Dashboard
    "agency.badge": "代理店ダッシュボード",
    "agency.title": "案件管理",
    "agency.subtitle": "すべての診断・候補地を一元管理します。",
    "agency.newDiagnosis": "新規診断",
    "agency.addCandidate": "候補地追加",
    "agency.totalCases": "総案件数",
    "agency.completed": "診断完了",
    "agency.processing": "処理中",
    "agency.candidates": "出店候補地",
    "agency.searchPh": "店舗名・業種で検索...",
    "agency.statusAll": "すべて",
    "agency.statusCompleted": "完了",
    "agency.statusProcessing": "処理中",
    "agency.statusDraft": "下書き",
    "agency.colType": "種別",
    "agency.colStore": "店舗名",
    "agency.colIndustry": "業種",
    "agency.colDate": "分析日時",
    "agency.colStatus": "ステータス",
    "agency.colAction": "操作",
    "agency.typeDiagnosis": "診断",
    "agency.typeCandidate": "候補地",
    "agency.details": "詳細",
    "agency.noCases": "該当する案件がありません",

    // Report
    "report.badge": "統合レポート",
    "report.title": "分析レポート",
    "report.subtitle": "商圏分析・推奨施策・広告配分・チラシ出稿案を1ページで確認できます。",
    "report.address": "住所",
    "report.industry": "業種",
    "report.storeName": "店舗名（任意）",
    "report.monthlyBudget": "月間予算（任意）",
    "report.target": "ターゲット（任意）",
    "report.generating": "レポート生成中...",
    "report.generate": "統合レポートを作成",
    "report.areaAnalysis": "商圏分析結果",
    "report.recActions": "推奨施策",
    "report.adBudget": "広告予算配分",
    "report.flyerPlan": "チラシ出稿案",
    "report.areaLabel": "エリア",
    "report.estPop": "推定人口",
    "report.estHouseholds": "推定世帯数",
    "report.mainTarget": "主要ターゲット",
    "report.competitiveEnv": "競合環境",
    "report.monthlyBudgetLabel": "月間予算",
    "report.monthlyTotalBudget": "月間合計予算",
    "report.totalQty": "合計部数",
    "report.totalCost": "合計費用",
    "report.expectedResponse": "期待反応率",
    "report.expectedROI": "期待ROI",
    "report.recQty": "推奨部数",
    "report.targetDesc": "ターゲット",
    "report.reportComplete": "レポートが完成しました",
    "report.reportFailed": "レポート生成に失敗しました",
    "report.runningAI": "3つのAI分析を同時実行中...",
    "report.recommended": "推奨",

    // Store Candidates
    "sc.badge": "出店候補地管理",
    "sc.title": "出店候補地の登録",
    "sc.subtitle": "出店を検討しているエリアを登録し、商圏分析や媒体プランに活用できます。",
    "sc.addNew": "新しい候補地を追加",
    "sc.closeForm": "フォームを閉じる",
    "sc.formTitle": "候補地情報を入力",
    "sc.formDesc": "できるだけ詳しく入力すると、分析精度が向上します。",
    "sc.storeName": "店舗名",
    "sc.industry": "業種",
    "sc.address": "住所",
    "sc.latitude": "緯度（任意）",
    "sc.longitude": "経度（任意）",
    "sc.memo": "出店候補地メモ（任意）",
    "sc.registering": "登録中...",
    "sc.register": "候補地を登録",
    "sc.noData": "候補地がまだありません",
    "sc.noDataDesc": "出店を検討しているエリアを登録しましょう。",
    "sc.addFirst": "最初の候補地を追加",
    "sc.registered": "出店候補地を登録しました",
    "sc.deleted": "候補地を削除しました",
    "sc.fetchError": "データの取得に失敗しました",
    "sc.draft": "下書き",

    // Store Input
    "si.badge": "店舗情報入力",
    "si.title": "店舗の情報を教えてください",
    "si.subtitle": "入力内容をもとに、AIが集客診断と施策を提案します。",
    "si.basicInfo": "基本情報",
    "si.basicInfoDesc": "できるだけ詳しく入力いただくと、より精度の高い診断が可能です。",
    "si.storeName": "店舗名",
    "si.industry": "業種",
    "si.address": "住所",
    "si.station": "最寄駅",
    "si.target": "ターゲット層",
    "si.strengths": "店の強み",
    "si.concerns": "現在の悩み",
    "si.adBudget": "月の広告・販促予算",
    "si.competitors": "競合店舗",
    "si.mediaLabel": "利用したい媒体（複数選択可）",
    "si.submitting": "AIが分析中…（30秒ほどかかります）",
    "si.submit": "診断を開始する",
    "si.aiStarted": "AIが診断を開始しました…",
    "si.diagComplete": "診断が完了しました！",
    "si.diagFailed": "診断の開始に失敗しました",
    "si.enterStoreName": "店舗名を入力してください",
    "si.enterIndustry": "業種を入力してください",
    "si.enterAddress": "住所を入力してください",
    "si.mediaGBP": "Googleビジネスプロフィール",
    "si.mediaIG": "Instagram",
    "si.mediaX": "X（Twitter）",
    "si.mediaLINE": "LINE公式アカウント",
    "si.mediaFlyer": "チラシ・ポスティング",
    "si.mediaWebAd": "Web広告（Google/Meta）",
    "si.mediaPortal": "食べログ・ホットペッパー等",

    // Dashboard subscription
    "dash.subBadge.free": "フリープラン",
    "dash.subBadge.pro": "プロプラン",
    "dash.subBadge.until": "まで",

    // Admin
    "nav.admin": "管理者",
    "admin.title": "管理者ダッシュボード",
    "admin.payments": "課金履歴",
    "admin.whitelist": "無料ホワイトリスト",
    "admin.totalRevenue": "合計売上",
    "admin.totalPayments": "決済件数",
    "admin.paymentHistory": "決済履歴",
    "admin.date": "日時",
    "admin.email": "メールアドレス",
    "admin.amount": "金額",
    "admin.status": "ステータス",
    "admin.noPayments": "決済履歴がありません",
    "admin.addWhitelist": "ホワイトリストに追加",
    "admin.addWhitelistDesc": "指定したメールアドレスのユーザーは無料で無制限に利用できます。",
    "admin.emailPh": "メールアドレス",
    "admin.notePh": "メモ（任意）",
    "admin.add": "追加",
    "admin.whitelistTitle": "ホワイトリスト一覧",
    "admin.note": "メモ",
    "admin.addedDate": "追加日",
    "admin.noWhitelist": "ホワイトリストにメールアドレスがありません",
    "admin.whitelistAdded": "ホワイトリストに追加しました",
    "admin.whitelistRemoved": "ホワイトリストから削除しました",
    "admin.noAccess": "管理者権限がありません",
    "admin.backHome": "ホームに戻る",
    "usage.limitReached": "今月の無料診断回数に達しました",
    "usage.upgradeHint": "Proプランにアップグレードすると無制限にご利用いただけます。",
    "usage.viewPlans": "プランを見る",
    "usage.monthly": "今月の利用",

    // Footer
    "footer.tokushoho": "特定商取引法に基づく表記",
    "footer.terms": "利用規約",

    // Tokushoho
    "legal.title": "特定商取引法に基づく表記",
    "legal.seller": "販売業者",
    "legal.sellerVal": "株式会社ビヨンド",
    "legal.representative": "代表責任者",
    "legal.representativeVal": "代表取締役 上野淳",
    "legal.address": "所在地",
    "legal.addressVal": "東京都新宿区新宿5-4-1",
    "legal.contact": "お問い合わせ",
    "legal.contactLink": "お問い合わせフォームはこちら",
    "legal.price": "販売価格",
    "legal.priceVal": "各プランページに表示された価格（税込）に準じます。",
    "legal.payment": "お支払い方法",
    "legal.paymentVal": "クレジットカード（Stripe経由）",
    "legal.delivery": "サービス提供時期",
    "legal.deliveryVal": "お支払い確認後、即時ご利用いただけます。",
    "legal.cancel": "解約・退会",
    "legal.cancelVal": "マイページからいつでも解約できます。解約後も当月末までご利用いただけます。",
    "legal.refund": "返品・返金",
    "legal.refundVal": "デジタルサービスの性質上、原則として返金は行いません。",

    // Terms
    "terms.title": "利用規約",
    "terms.lastUpdated": "最終更新日: 2025年4月6日",
    "terms.s1.title": "（適用）",
    "terms.s1.body": "本規約は、株式会社ビヨンド（以下「当社」）が提供するMapBoost AI（以下「本サービス」）の利用に関する条件を定めるものです。ユーザーは本規約に同意の上、本サービスを利用するものとします。",
    "terms.s2.title": "（利用登録）",
    "terms.s2.body": "ユーザーは、当社所定の方法により利用登録を行うものとします。当社は、登録を承認した時点で利用契約が成立するものとします。",
    "terms.s3.title": "（料金および支払い）",
    "terms.s3.body": "有料プランの料金は、料金ページに記載のとおりとします。支払いはクレジットカードにより、毎月自動課金されます。",
    "terms.s4.title": "（禁止事項）",
    "terms.s4.body": "ユーザーは以下の行為を行ってはなりません。\n・法令または公序良俗に反する行為\n・当社または第三者の権利を侵害する行為\n・本サービスの運営を妨害する行為\n・不正アクセスまたはそれを試みる行為\n・その他、当社が不適切と判断する行為",
    "terms.s5.title": "（サービスの変更・中断・終了）",
    "terms.s5.body": "当社は、事前の通知なく本サービスの内容を変更、中断、または終了することがあります。これによりユーザーに生じた損害について、当社は一切責任を負いません。",
    "terms.s6.title": "（免責事項）",
    "terms.s6.body": "本サービスで提供される分析結果・提案内容はAIにより生成されたものであり、その正確性・完全性を保証するものではありません。ユーザーは自己の責任において本サービスを利用するものとします。",
    "terms.s7.title": "（個人情報の取扱い）",
    "terms.s7.body": "当社は、ユーザーの個人情報を適切に管理し、本サービスの提供・改善目的以外に利用しません。",
    "terms.s8.title": "（準拠法・管轄）",
    "terms.s8.body": "本規約は日本法に準拠し、本規約に関する紛争は東京地方裁判所を第一審の専属的合意管轄裁判所とします。",

    // Contact
    "footer.contact": "お問い合わせ",
    "contact.title": "お問い合わせ",
    "contact.subtitle": "ご質問・ご要望がありましたら、以下のフォームからお気軽にお問い合わせください。",
    "contact.name": "お名前",
    "contact.namePh": "山田 太郎",
    "contact.email": "メールアドレス",
    "contact.emailPh": "taro@example.com",
    "contact.message": "お問い合わせ内容",
    "contact.messagePh": "お問い合わせ内容をご記入ください...",
    "contact.send": "送信する",
    "contact.required": "すべての項目を入力してください",
    "contact.success": "お問い合わせを送信しました。ありがとうございます。",
    "contact.error": "送信に失敗しました。もう一度お試しください。",
    "contact.thankYou": "送信完了",
    "contact.thankYouDesc": "お問い合わせありがとうございます。内容を確認の上、ご連絡いたします。",

    // Agency Dashboard
    "agency.newDiag": "新規診断",
    "agency.totalItems": "総案件数",
    "agency.pending": "処理中",
    "agency.status": "ステータス",
    "agency.all": "すべて",
    "agency.statusPending": "処理中",
    "agency.noItems": "該当する案件がありません",
    "agency.typeDiag": "診断",
    "agency.detail": "詳細",

    // Location Match
    "loc.industryPh": "例: 美容院、カフェ、学習塾",
    "loc.budget": "予算規模（任意）",
    "loc.budgetPh": "例: 初期投資500万円、月額30万円",
    "loc.location": "希望エリア・現在地（任意）",
    "loc.locationPh": "例: 東京都内、大阪市周辺",
    "loc.target": "ターゲット層（任意）",
    "loc.targetPh": "例: 20〜30代女性、ファミリー層",
    "loc.service": "サービス内容",
    "loc.servicePh": "例: オーガニック食材を使ったヘルシーカフェ。テイクアウトとイートイン両対応。",
    "loc.prefs": "その他の条件（任意）",
    "loc.prefsPh": "例: 駅徒歩5分以内、家賃は月30万円以下",
    "loc.pdfDownload": "PDFダウンロード",
    "loc.errIndustry": "業種を入力してください",
    "loc.errService": "サービス内容を入力してください",
    "loc.success": "エリアマッチング分析が完了しました",
    "loc.error": "分析に失敗しました",
    "loc.summaryTitle": "分析結果の概要",
    "loc.aiRecommend": "AIの最終推奨",
    "loc.budgetGuide": "初期投資目安",
    "loc.ranking": "推奨エリアランキング",
    "loc.pts": "点",
    "loc.population": "推定人口",
    "loc.rent": "家賃相場",
    "loc.tabStore": "出店",
    "loc.tabAd": "広告",
    "loc.tabFlyer": "チラシ",
    "loc.thArea": "エリア",
    "loc.thScore": "スコア",
    "loc.thComp": "競合",
    "loc.thTarget": "ターゲット適合",
    "loc.thCost": "コスト効率",
    "loc.thGrowth": "成長性",

    // Media Plan
    "media.address": "店舗所在地",
    "media.addressPh": "例: 東京都渋谷区神南1丁目",
    "media.industryPh": "例: 美容院、学習塾",
    "media.storeNamePh": "例: ヘアサロン BLOOM",
    "media.budget": "月間予算（任意）",
    "media.budgetPh": "例: 10万円",
    "media.target": "ターゲット層（任意）",
    "media.targetPh": "例: 30〜40代の子育て世帯",
    "media.pdfDownload": "PDFダウンロード",
    "media.errAddress": "住所を入力してください",
    "media.errIndustry": "業種を入力してください",
    "media.success": "媒体プランが完成しました",
    "media.error": "プラン生成に失敗しました",
    "media.copied": "コピーしました",
    "media.tabMeta": "Meta広告",
    "media.tabGoogle": "Google広告",
    "media.tabFlyer": "チラシ",
    "media.expectedCPM": "期待CPM / CTR",
    "media.noMeta": "Meta広告データがありません",
    "media.expectedCTR": "期待CTR / CPA",
    "media.keywords": "推奨キーワード",
    "media.adCopy": "広告文案",
    "media.noGoogle": "Google広告データがありません",
    "media.responseRate": "期待反応率",
    "media.households": "世帯数",
    "media.timing": "配布タイミング",
    "media.catchcopy": "キャッチコピー案",
    "media.noFlyer": "チラシデータがありません",

    // Report
    "rpt.badge": "統合レポート",
    "rpt.title": "分析レポート",
    "rpt.subtitle": "商圏分析・推奨施策・広告配分・チラシ出稿案を1ページで確認できます。",
    "rpt.address": "住所",
    "rpt.addressPh": "例: 東京都渋谷区神南1丁目",
    "rpt.industry": "業種",
    "rpt.industryPh": "例: 美容院、カフェ",
    "rpt.storeName": "店舗名（任意）",
    "rpt.storeNamePh": "例: ヘアサロン BLOOM",
    "rpt.budget": "月間予算（任意）",
    "rpt.budgetPh": "例: 10万円",
    "rpt.target": "ターゲット（任意）",
    "rpt.targetPh": "例: 20〜30代女性",
    "rpt.generating": "レポート生成中...",
    "rpt.generate": "統合レポートを作成",
    "rpt.pdfDownload": "PDFダウンロード",
    "rpt.errAddress": "住所を入力してください",
    "rpt.errIndustry": "業種を入力してください",
    "rpt.success": "レポートが完成しました",
    "rpt.error": "レポート生成に失敗しました",
    "rpt.errorTitle": "レポート生成に失敗しました",
    "rpt.loadingMsg": "3つのAI分析を同時実行中...",
    "rpt.sArea": "商圏分析結果",
    "rpt.areaName": "エリア",
    "rpt.pop": "推定人口",
    "rpt.hh": "推定世帯数",
    "rpt.mainTarget": "主要ターゲット",
    "rpt.compEnv": "競合環境",
    "rpt.sActions": "推奨施策",
    "rpt.recommended": "推奨",
    "rpt.sBudget": "広告予算配分",
    "rpt.monthlyBudget": "月間予算",
    "rpt.total": "合計",
    "rpt.monthlyTotal": "月間合計予算",
    "rpt.expectedROAS": "期待ROAS",
    "rpt.sFlyer": "チラシ出稿案",
    "rpt.totalQty": "合計部数",
    "rpt.totalCost": "合計費用",
    "rpt.responseRate": "期待反応率",
    "rpt.expectedROI": "期待ROI",
    "rpt.recQty": "推奨部数",
    "rpt.targetLabel": "ターゲット",

    // Store Candidates
    "sc.storeNamePh": "例: カフェ モカ 渋谷店",
    "sc.industryPh": "例: カフェ・喫茶店",
    "sc.addressPh": "例: 東京都渋谷区道玄坂1-2-3",
    "sc.lat": "緯度（任意）",
    "sc.latPh": "例: 35.6595",
    "sc.lng": "経度（任意）",
    "sc.lngPh": "例: 139.7004",
    "sc.memoPh": "例: 駅前ロータリー正面、人通り多い。近隣に競合カフェ2店舗あり。",
    "sc.errName": "店舗名を入力してください",
    "sc.errIndustry": "業種を入力してください",
    "sc.errAddress": "住所を入力してください",
    "sc.created": "出店候補地を登録しました",
    "sc.empty": "候補地がまだありません",
    "sc.emptyDesc": "出店を検討しているエリアを登録しましょう。",

    // Store Input
    "si.storeNamePh": "例：カフェ モカ 渋谷店",
    "si.industryPh": "例：カフェ・喫茶店",
    "si.addressPh": "例：東京都渋谷区道玄坂1-2-3",
    "si.stationPh": "例：渋谷駅 徒歩5分",
    "si.targetPh": "例：20〜30代 会社員・フリーランス",
    "si.strengthsPh": "例：自家焙煎コーヒー、Wi-Fi完備、電源あり",
    "si.concernsPh": "例：平日昼間の集客が弱い、SNS活用ができていない",
    "si.budget": "月の広告・販促予算",
    "si.budgetPh": "例：5万円〜10万円",
    "si.competitorsPh": "例：スターバックス渋谷店、タリーズ道玄坂店",
    "si.media": "利用したい媒体（複数選択可）",
    "si.analyzing": "AIが分析中…（30秒ほどかかります）",
    "si.start": "診断を開始する",
    "si.errName": "店舗名を入力してください",
    "si.errIndustry": "業種を入力してください",
    "si.errAddress": "住所を入力してください",
    "si.limitMsg": "今月の無料診断回数（3回）に達しました。Proプランにアップグレードしてください。",
    "si.complete": "診断が完了しました！",
    "si.error": "診断の開始に失敗しました",
    "si.times": "回",
  },
  en: {
    // Nav & Layout
    "nav.home": "Home",
    "nav.analysis": "Analysis",
    "nav.promotion": "Promotion",
    "nav.management": "Management",
    "nav.diagnosis": "Diagnosis",
    "nav.areaAnalysis": "Trade Area Analysis",
    "nav.locationMatch": "Location Match",
    "nav.storeCandidates": "Store Candidates",
    "nav.mediaPlan": "Integrated Media Plan",
    "nav.adProposal": "Ad Proposal",
    "nav.flyerPlan": "Flyer Planning",
    "nav.agencyDashboard": "Agency Dashboard",
    "nav.report": "Integrated Report",
    "nav.diagnosisList": "Diagnosis List",
    "nav.storeInput": "Store Input (Diagnosis)",
    "nav.logout": "Logout",
    "nav.login": "Login",
    "footer.copyright": "© 2026 MapBoost AI",
    "footer.description": "Local Marketing Analysis Tool — Area Analysis, Store Analysis, Ad Proposals, Flyer Distribution",

    // Index / Hero
    "hero.badge": "Map-Driven Store Marketing AI",
    "hero.title1": "Find the best",
    "hero.title2": "marketing strategy for",
    "hero.title3": "your store in minutes",
    "hero.description": "Simply enter your store info and AI will create a marketing plan based on your trade area, customers, and competitors.",
    "hero.cta": "Start Free Diagnosis",
    "hero.loginBtn": "Login",
    "hero.visitRate": "Visit Rate",
    "hero.awareness": "Awareness",
    "features.badge": "Key Features",
    "features.title": "What MapBoost AI Can Do",
    "features.description": "Enter your store info and get 6 automated analyses and recommendations.",
    "feature.diagnosis.title": "Marketing Diagnosis",
    "feature.diagnosis.desc": "Analyze trade area, customers, and competitors to visualize strengths and weaknesses.",
    "feature.area.title": "Trade Area Analysis",
    "feature.area.desc": "AI analyzes demographics, age distribution, and households within 1-5km radius.",
    "feature.candidates.title": "Store Candidate Management",
    "feature.candidates.desc": "Register and manage potential store locations with trade area scoring.",
    "feature.media.title": "Media Plan",
    "feature.media.desc": "AI recommends optimal budget allocation for Meta, Google, and flyers.",
    "feature.agency.title": "Agency Dashboard",
    "feature.agency.desc": "Manage client and store analysis projects at a glance with status tracking.",
    "feature.report.title": "Integrated Report",
    "feature.report.desc": "Consolidate area analysis, strategies, ads, and flyers into one page. PDF export supported.",
    "steps.title": "4 Easy Steps",
    "steps.description": "From input to execution in just a few minutes.",
    "step1.title": "Enter Store Info",
    "step1.desc": "Input industry, address, strengths, and concerns",
    "step2.title": "AI Analyzes & Suggests",
    "step2.desc": "Get diagnosis results and strategies in seconds",
    "step3.title": "Generate Promo Copy",
    "step3.desc": "Create copy for each channel with one click",
    "step4.title": "Execute & Improve",
    "step4.desc": "Run and refine strategies using KPI tracking",
    "cta.title": "Try a free diagnosis today",
    "cta.description": "Takes about 3 minutes. Start right after signing up.",

    // Auth
    "auth.title": "MapBoost AI",
    "auth.subtitle": "Login or create a new account",
    "auth.loginTab": "Login",
    "auth.signupTab": "Sign Up",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.passwordHint": "Password (6+ characters)",
    "auth.loginBtn": "Login",
    "auth.signupBtn": "Create Account",
    "auth.processing": "Processing…",
    "auth.or": "or",
    "auth.googleLogin": "Login with Google",
    "auth.googleSignup": "Sign up with Google",
    "auth.loginFailed": "Login failed. Please check your email and password.",
    "auth.signupSuccess": "Confirmation email sent. Please check your inbox.",
    "auth.googleFailed": "Google login failed",
    "loading": "Loading...",

    // Store Input
    "store.badge": "Store Information",
    "store.title": "Tell us about your store",
    "store.description": "AI will suggest marketing strategies based on your input.",
    "store.basicInfo": "Basic Information",
    "store.basicInfoDesc": "The more detail you provide, the more accurate the diagnosis.",
    "store.name": "Store Name",
    "store.industry": "Industry",
    "store.address": "Address",
    "store.station": "Nearest Station",
    "store.target": "Target Audience",
    "store.strengths": "Store Strengths",
    "store.concerns": "Current Concerns",
    "store.budget": "Monthly Ad/Promo Budget",
    "store.competitors": "Competitors",
    "store.media": "Channels to Use (select multiple)",
    "store.submit": "Start Diagnosis",
    "store.submitting": "AI is analyzing… (about 30 seconds)",
    "store.aiStarted": "AI diagnosis started…",
    "store.completed": "Diagnosis completed!",
    "store.failed": "Failed to start diagnosis",

    // Diagnosis
    "diag.badge": "Diagnosis Results",
    "diag.title": " Marketing Diagnosis",
    "diag.subtitle": "Recommended strategies based on AI analysis.",
    "diag.notFound": "Diagnosis results not found",
    "diag.generating": "Generating diagnosis results…",
    "diag.backToDashboard": "Back to Dashboard",
    "diag.strengths": "Store Strengths",
    "diag.weaknesses": "Weaknesses / Issues",
    "diag.targetCustomers": "Target Customer Segments",
    "diag.differentiation": "Differentiation Points",
    "diag.bottlenecks": "Marketing Bottlenecks",
    "diag.bottlenecksDesc": "Key factors hindering customer acquisition",
    "diag.actions": "Actions to Take Now",
    "diag.estimatedCost": "Est. Cost",
    "diag.difficulty": "Difficulty",
    "diag.expectedEffect": "Expected Effect",
    "diag.pdfExport": "Export PDF",
    "diag.viewPromo": "View Promo Copy",
    "diag.viewKpi": "View KPI Plan",

    // PromoText
    "promo.title": "Auto-Generated Promo Copy",
    "promo.subtitle": "— Promo copy by channel",
    "promo.generating": "Generating promo copy…",
    "promo.dataNotFound": "Data not found",
    "promo.copy": "Copy",
    "promo.copied": "Copied to clipboard",
    "promo.softer": "Softer",
    "promo.stronger": "Stronger",
    "promo.alternative": "Alternative",
    "promo.regenerate": "Regenerate Promo Copy",
    "promo.regenerated": "Promo copy regenerated",
    "promo.regenerateFailed": "Regeneration failed",
    "promo.adjustedSoft": "Adjusted to softer tone",
    "promo.adjustedStrong": "Adjusted to stronger tone",
    "promo.adjustedAlt": "Alternative generated",
    "promo.adjustFailed": "Adjustment failed",

    // KPI
    "kpi.badge": "KPI Design",
    "kpi.title": " KPI Design",
    "kpi.subtitle": "Metrics and targets to measure strategy effectiveness",
    "kpi.generating": "Generating KPI design…",
    "kpi.target": "Target",
    "kpi.measurement": "Measurement",
    "kpi.frequency": "Review Frequency",

    // Dashboard
    "dash.badge": "Dashboard",
    "dash.title": "Diagnosis Management",
    "dash.subtitle": "Review and manage past diagnosis reports.",
    "dash.newDiagnosis": "Create New Diagnosis",
    "dash.noDiagnosis": "No diagnoses yet",
    "dash.noDiagnosisDesc": "Enter your store info to start an AI-powered marketing diagnosis.",
    "dash.createFirst": "Create First Diagnosis",
    "dash.totalDiagnoses": "Total Diagnoses",
    "dash.completed": "Completed",
    "dash.thisMonth": "This Month",
    "dash.latest": "Latest",
    "dash.trendTitle": "Diagnosis Trend (Last 6 Months)",
    "dash.noTrendData": "No diagnosis data yet",
    "dash.totalCount": "Total",
    "dash.completedCount": "Completed",
    "dash.report": "Report",
    "dash.promoText": "Promo Copy",
    "dash.status.completed": "Done",
    "dash.status.processing": "Processing",
    "dash.status.pending": "Creating",
    "dash.status.error": "Error",
    "dash.strengthsCount": "Strengths",
    "dash.actionsCount": "Actions",
    "dash.createdOn": " created",

    // Area Analysis
    "area.badge": "Area Analysis",
    "area.title": "Trade Area & Store Analysis",
    "area.subtitle": "Enter an address and let AI analyze demographics and market potential.",
    "area.tabArea": "Trade Area",
    "area.tabOpening": "Store Opening",
    "area.address": "Address / Area Name",
    "area.addressPh": "e.g. 1 Jinnan, Shibuya, Tokyo",
    "area.radius": "Trade Area Radius",
    "area.industry": "Industry",
    "area.industryOptional": " (optional)",
    "area.industryPh": "e.g. Café, Tutoring, Salon",
    "area.analyzing": "Analyzing...",
    "area.analyze": "Analyze with AI",
    "area.pdfDownload": "Download PDF",
    "area.realData": "Real Data",
    "area.aiEstimate": "AI Estimate",
    "area.censusTitle": "Census Data",
    "area.source": "Source",
    "area.areaCode": "Area Code",
    "area.totalPop": "Total Population",
    "area.households": "Households",
    "area.dataSource": "Data Source",
    "area.ageComp": "Age Distribution",
    "area.ageCompReal": "Age Distribution (Real Data)",
    "area.areaLabel": "Area",
    "area.estPop": "Est. Population",
    "area.estHouseholds": "Est. Households",
    "area.radiusLabel": "Radius",
    "area.areaFeatures": "Area Characteristics",
    "area.mainTarget": "Primary Target",
    "area.householdComp": "Household Types",
    "area.suitableInd": "Suitable Industries",
    "area.unsuitableInd": "Unsuitable Industries",
    "area.visitMotivations": "Visit Motivations",
    "area.competition": "Competitive Environment",
    "area.successProb": "Success Probability",
    "area.scoreBreakdown": "Score Breakdown",
    "area.targetCustomer": "Target Customer",
    "area.unitPrice": "Est. Unit Price",
    "area.visitFreq": "Est. Visit Frequency",
    "area.riskFactors": "Risk Factors",
    "area.improvements": "Improvement Advice",
    "area.risk": "Risk",
    "area.countermeasure": "Mitigation",
    "area.enterAddress": "Please enter an address",
    "area.enterIndustry": "Please enter an industry",
    "area.analysisComplete": "Analysis complete",
    "area.analysisCompleteReal": "Analysis complete based on census data",
    "area.analysisCompleteFallback": "Analysis complete (AI estimate)",
    "area.analysisFailed": "Analysis failed",
    "area.radius1km": "1km Radius",
    "area.radius3km": "3km Radius",
    "area.radius5km": "5km Radius",
    "area.people": " people",
    "area.householdsUnit": " households",
    "area.population": "Population",
    "area.percentage": "Proportion",

    // Flyer Plan
    "flyer.badge": "Flyer Distribution",
    "flyer.title": "Flyer Distribution Planner",
    "flyer.subtitle": "AI designs optimal distribution areas, quantities, and catchphrases.",
    "flyer.storeLocation": "Store Location",
    "flyer.industry": "Industry",
    "flyer.storeName": "Store Name (optional)",
    "flyer.budget": "Budget Estimate (optional)",
    "flyer.targetAudience": "Target Audience (optional)",
    "flyer.generating": "Generating plan...",
    "flyer.generate": "Create Distribution Plan with AI",
    "flyer.summary": "Distribution Plan Overview",
    "flyer.totalQty": "Total Quantity",
    "flyer.totalCost": "Total Cost",
    "flyer.expectedResponse": "Expected Response Rate",
    "flyer.expectedROI": "Expected ROI",
    "flyer.distAreas": "Distribution Area Plan",
    "flyer.priority": "Priority",
    "flyer.estHouseholds": "Est. Households",
    "flyer.targetDesc": "Target",
    "flyer.areaDistChart": "Distribution by Area",
    "flyer.costBreakdown": "Cost Breakdown",
    "flyer.printUnit": "Print Unit Cost",
    "flyer.distUnit": "Dist. Unit Cost",
    "flyer.printTotal": "Total Print Cost",
    "flyer.distTotal": "Total Dist. Cost",
    "flyer.total": "Total",
    "flyer.timing": "Distribution Timing",
    "flyer.bestDays": "Best Days",
    "flyer.bestTime": "Best Time Slots",
    "flyer.frequency": "Recommended Frequency",
    "flyer.seasonalTips": "Seasonal Advice",
    "flyer.catchcopies": "Catchphrase Ideas",
    "flyer.designTips": "Design Advice",
    "flyer.copies": " copies",
    "flyer.perSheet": "/sheet",
    "flyer.planComplete": "Flyer distribution plan completed",
    "flyer.planFailed": "Failed to generate plan",

    // Ad Proposal
    "ad.badge": "Ad Proposal",
    "ad.title": "Ad Planner",
    "ad.subtitle": "AI designs optimal plans for Google Ads and Meta Ads.",
    "ad.storeLocation": "Store Location",
    "ad.industry": "Industry",
    "ad.storeName": "Store Name (optional)",
    "ad.monthlyBudget": "Monthly Ad Budget (optional)",
    "ad.targetAudience": "Target Audience (optional)",
    "ad.generating": "Generating proposal...",
    "ad.generate": "Create Ad Proposal with AI",
    "ad.strategySummary": "Ad Strategy Overview",
    "ad.recPlatform": "Recommended Platform",
    "ad.monthlyTotal": "Monthly Total Budget",
    "ad.expectedROAS": "Expected ROAS",
    "ad.googleCPA": "Google CPA",
    "ad.googleAds": "Google Ads",
    "ad.metaAds": "Meta Ads",
    "ad.campaignType": "Campaign Type",
    "ad.dailyBudget": "Daily Budget",
    "ad.expectedCTR": "Expected CTR",
    "ad.recKeywords": "Recommended Keywords",
    "ad.adCopies": "Ad Copy",
    "ad.campaignObj": "Campaign Objective",
    "ad.expectedCPM_CTR": "Expected CPM / CTR",
    "ad.targetAudiences": "Target Audiences",
    "ad.age": "Age",
    "ad.gender": "Gender",
    "ad.adCreatives": "Ad Creative Ideas",
    "ad.overallStrategy": "Overall Strategy & Tips",
    "ad.recommended": "Recommended",
    "ad.proposalComplete": "Ad proposal completed",
    "ad.proposalFailed": "Failed to generate proposal",

    // Location Match
    "loc.badge": "Area Matching",
    "loc.title": "Location Matching",
    "loc.subtitle": "AI suggests the best areas for your store, ads, and flyer distribution.",
    "loc.industry": "Industry",
    "loc.budgetScale": "Budget Scale (optional)",
    "loc.preferredArea": "Preferred Area / Current Location (optional)",
    "loc.targetAudience": "Target Audience (optional)",
    "loc.serviceDesc": "Service Description",
    "loc.otherConditions": "Other Preferences (optional)",
    "loc.analyzing": "Analyzing areas...",
    "loc.analyze": "Run AI Area Matching",
    "loc.analysisSummary": "Analysis Summary",
    "loc.aiFinalRec": "AI's Top Recommendation",
    "loc.investmentGuide": "Est. Initial Investment",
    "loc.areaRanking": "Recommended Area Ranking",
    "loc.estPop": "Est. Population",
    "loc.mainTarget": "Main Target",
    "loc.competitionDensity": "Competition Level",
    "loc.rentEstimate": "Rent Estimate",
    "loc.monthlyCustomers": "Est. Monthly Customers",
    "loc.strengths": "Strengths",
    "loc.risks": "Risks",
    "loc.storeTab": "Store",
    "loc.adTab": "Ads",
    "loc.flyerTab": "Flyers",
    "loc.compTable": "Area Comparison Table",
    "loc.area": "Area",
    "loc.score": "Score",
    "loc.competition": "Competition",
    "loc.targetFit": "Target Fit",
    "loc.costEff": "Cost Efficiency",
    "loc.growth": "Growth Potential",
    "loc.actionPlan": "Action Plan",
    "loc.matchComplete": "Area matching analysis completed",
    "loc.matchFailed": "Analysis failed",
    "loc.enterIndustry": "Please enter an industry",
    "loc.enterService": "Please enter service description",
    "loc.points": "pts",

    // Media Plan
    "media.badge": "Media Plan",
    "media.title": "Integrated Media Planner",
    "media.subtitle": "Plan Google Ads, Meta Ads, and flyer distribution all at once.",
    "media.storeLocation": "Store Location",
    "media.industry": "Industry",
    "media.storeName": "Store Name (optional)",
    "media.monthlyBudget": "Monthly Budget (optional)",
    "media.targetAudience": "Target Audience (optional)",
    "media.generating": "Generating plan...",
    "media.generate": "Create Integrated Media Plan",
    "media.metaAds": "Meta Ads",
    "media.googleAds": "Google Ads",
    "media.flyer": "Flyers",
    "media.campaignObj": "Campaign Objective",
    "media.dailyBudget": "Daily Budget",
    "media.expectedCPM_CTR": "Expected CPM / CTR",
    "media.campaignType": "Campaign Type",
    "media.expectedCTR_CPA": "Expected CTR / CPA",
    "media.recKeywords": "Recommended Keywords",
    "media.adCopies": "Ad Copy",
    "media.totalQty": "Total Quantity",
    "media.totalCost": "Total Cost",
    "media.expectedResponse": "Expected Response Rate",
    "media.distAreas": "Distribution Areas",
    "media.distTiming": "Distribution Timing",
    "media.bestDays": "Best Days",
    "media.bestTime": "Best Time Slots",
    "media.frequency": "Recommended Frequency",
    "media.catchcopies": "Catchphrase Ideas",
    "media.noMetaData": "No Meta Ads data",
    "media.noGoogleData": "No Google Ads data",
    "media.noFlyerData": "No flyer data",
    "media.planComplete": "Media plan completed",
    "media.planFailed": "Failed to generate plan",
    "media.age": "Age",
    "media.gender": "Gender",
    "media.householdCount": "Households",
    "media.recQty": "Rec. Quantity",

    // Agency Dashboard
    "agency.badge": "Agency Dashboard",
    "agency.title": "Project Management",
    "agency.subtitle": "Manage all diagnoses and store candidates in one place.",
    "agency.newDiagnosis": "New Diagnosis",
    "agency.addCandidate": "Add Candidate",
    "agency.totalCases": "Total Projects",
    "agency.completed": "Completed",
    "agency.processing": "Processing",
    "agency.candidates": "Store Candidates",
    "agency.searchPh": "Search by store name or industry...",
    "agency.statusAll": "All",
    "agency.statusCompleted": "Completed",
    "agency.statusProcessing": "Processing",
    "agency.statusDraft": "Draft",
    "agency.colType": "Type",
    "agency.colStore": "Store Name",
    "agency.colIndustry": "Industry",
    "agency.colDate": "Analysis Date",
    "agency.colStatus": "Status",
    "agency.colAction": "Action",
    "agency.typeDiagnosis": "Diagnosis",
    "agency.typeCandidate": "Candidate",
    "agency.details": "Details",
    "agency.noCases": "No matching projects found",

    // Report
    "report.badge": "Integrated Report",
    "report.title": "Analysis Report",
    "report.subtitle": "View trade area analysis, strategies, ad allocation, and flyer plans on one page.",
    "report.address": "Address",
    "report.industry": "Industry",
    "report.storeName": "Store Name (optional)",
    "report.monthlyBudget": "Monthly Budget (optional)",
    "report.target": "Target (optional)",
    "report.generating": "Generating report...",
    "report.generate": "Create Integrated Report",
    "report.areaAnalysis": "Trade Area Analysis",
    "report.recActions": "Recommended Strategies",
    "report.adBudget": "Ad Budget Allocation",
    "report.flyerPlan": "Flyer Distribution Plan",
    "report.areaLabel": "Area",
    "report.estPop": "Est. Population",
    "report.estHouseholds": "Est. Households",
    "report.mainTarget": "Main Target",
    "report.competitiveEnv": "Competitive Environment",
    "report.monthlyBudgetLabel": "Monthly Budget",
    "report.monthlyTotalBudget": "Monthly Total Budget",
    "report.totalQty": "Total Quantity",
    "report.totalCost": "Total Cost",
    "report.expectedResponse": "Expected Response Rate",
    "report.expectedROI": "Expected ROI",
    "report.recQty": "Rec. Quantity",
    "report.targetDesc": "Target",
    "report.reportComplete": "Report completed",
    "report.reportFailed": "Report generation failed",
    "report.runningAI": "Running 3 AI analyses simultaneously...",
    "report.recommended": "Recommended",

    // Store Candidates
    "sc.badge": "Store Candidates",
    "sc.title": "Store Candidate Registration",
    "sc.subtitle": "Register areas you're considering for new stores and use them for analysis.",
    "sc.addNew": "Add New Candidate",
    "sc.closeForm": "Close Form",
    "sc.formTitle": "Enter Candidate Information",
    "sc.formDesc": "More detail leads to better analysis accuracy.",
    "sc.storeName": "Store Name",
    "sc.industry": "Industry",
    "sc.address": "Address",
    "sc.latitude": "Latitude (optional)",
    "sc.longitude": "Longitude (optional)",
    "sc.memo": "Notes (optional)",
    "sc.registering": "Registering...",
    "sc.register": "Register Candidate",
    "sc.noData": "No candidates yet",
    "sc.noDataDesc": "Register areas you're considering for new stores.",
    "sc.addFirst": "Add First Candidate",
    "sc.registered": "Store candidate registered",
    "sc.deleted": "Candidate deleted",
    "sc.fetchError": "Failed to fetch data",
    "sc.draft": "Draft",

    // Store Input
    "si.badge": "Store Information",
    "si.title": "Tell us about your store",
    "si.subtitle": "AI will create a marketing diagnosis and strategy based on your input.",
    "si.basicInfo": "Basic Information",
    "si.basicInfoDesc": "More detail leads to a more accurate diagnosis.",
    "si.storeName": "Store Name",
    "si.industry": "Industry",
    "si.address": "Address",
    "si.station": "Nearest Station",
    "si.target": "Target Audience",
    "si.strengths": "Store Strengths",
    "si.concerns": "Current Concerns",
    "si.adBudget": "Monthly Ad/Promo Budget",
    "si.competitors": "Competitors",
    "si.mediaLabel": "Preferred Media (multiple)",
    "si.submitting": "AI analyzing… (approx. 30 seconds)",
    "si.submit": "Start Diagnosis",
    "si.aiStarted": "AI diagnosis started…",
    "si.diagComplete": "Diagnosis complete!",
    "si.diagFailed": "Failed to start diagnosis",
    "si.enterStoreName": "Please enter store name",
    "si.enterIndustry": "Please enter industry",
    "si.enterAddress": "Please enter address",
    "si.mediaGBP": "Google Business Profile",
    "si.mediaIG": "Instagram",
    "si.mediaX": "X (Twitter)",
    "si.mediaLINE": "LINE Official Account",
    "si.mediaFlyer": "Flyers / Posting",
    "si.mediaWebAd": "Web Ads (Google/Meta)",
    "si.mediaPortal": "Tabelog, HotPepper, etc.",

    // Dashboard subscription
    "dash.subBadge.free": "Free Plan",
    "dash.subBadge.pro": "Pro Plan",
    "dash.subBadge.until": "until",
    "nav.pricing": "Plans",

    // Admin
    "nav.admin": "Admin",
    "admin.title": "Admin Dashboard",
    "admin.payments": "Payment History",
    "admin.whitelist": "Free Whitelist",
    "admin.totalRevenue": "Total Revenue",
    "admin.totalPayments": "Total Payments",
    "admin.paymentHistory": "Payment History",
    "admin.date": "Date",
    "admin.email": "Email",
    "admin.amount": "Amount",
    "admin.status": "Status",
    "admin.noPayments": "No payments yet",
    "admin.addWhitelist": "Add to Whitelist",
    "admin.addWhitelistDesc": "Users with whitelisted emails can use all features for free.",
    "admin.emailPh": "Email address",
    "admin.notePh": "Note (optional)",
    "admin.add": "Add",
    "admin.whitelistTitle": "Whitelist Entries",
    "admin.note": "Note",
    "admin.addedDate": "Added",
    "admin.noWhitelist": "No whitelisted emails",
    "admin.whitelistAdded": "Added to whitelist",
    "admin.whitelistRemoved": "Removed from whitelist",
    "admin.noAccess": "Admin access required",
    "admin.backHome": "Back to Home",
    "usage.limitReached": "Monthly free diagnosis limit reached",
    "usage.upgradeHint": "Upgrade to Pro for unlimited access.",
    "usage.viewPlans": "View Plans",
    "usage.monthly": "This month",

    // Footer
    "footer.tokushoho": "Specified Commercial Transactions Act",
    "footer.terms": "Terms of Service",

    // Tokushoho
    "legal.title": "Specified Commercial Transactions Act Disclosure",
    "legal.seller": "Seller",
    "legal.sellerVal": "Beyond Inc.",
    "legal.representative": "Representative",
    "legal.representativeVal": "Jun Ueno, CEO",
    "legal.address": "Address",
    "legal.addressVal": "Shinjuku 5-4-1, Shinjuku-ku, Tokyo, Japan",
    "legal.contact": "Contact",
    "legal.contactLink": "Contact us here",
    "legal.price": "Pricing",
    "legal.priceVal": "As displayed on the pricing page (tax included).",
    "legal.payment": "Payment Method",
    "legal.paymentVal": "Credit card (via Stripe)",
    "legal.delivery": "Service Delivery",
    "legal.deliveryVal": "Available immediately after payment confirmation.",
    "legal.cancel": "Cancellation",
    "legal.cancelVal": "You can cancel anytime from your account page. Service remains active until the end of the billing period.",
    "legal.refund": "Refund Policy",
    "legal.refundVal": "Due to the nature of digital services, refunds are not provided as a general rule.",

    // Terms
    "terms.title": "Terms of Service",
    "terms.lastUpdated": "Last updated: April 6, 2025",
    "terms.s1.title": "(Scope)",
    "terms.s1.body": "These Terms govern the use of MapBoost AI (the \"Service\") provided by Beyond Inc. (the \"Company\"). By using the Service, you agree to these Terms.",
    "terms.s2.title": "(Registration)",
    "terms.s2.body": "Users shall register through the method prescribed by the Company. The usage agreement is established when the Company approves the registration.",
    "terms.s3.title": "(Fees and Payment)",
    "terms.s3.body": "Fees for paid plans are as listed on the pricing page. Payment is automatically charged monthly via credit card.",
    "terms.s4.title": "(Prohibited Activities)",
    "terms.s4.body": "Users shall not engage in the following:\n• Activities that violate laws or public morals\n• Activities that infringe the rights of the Company or third parties\n• Activities that interfere with the operation of the Service\n• Unauthorized access or attempts thereof\n• Other activities deemed inappropriate by the Company",
    "terms.s5.title": "(Service Changes/Suspension/Termination)",
    "terms.s5.body": "The Company may change, suspend, or terminate the Service without prior notice. The Company shall not be liable for any damages caused to users thereby.",
    "terms.s6.title": "(Disclaimer)",
    "terms.s6.body": "Analysis results and recommendations provided by the Service are generated by AI and are not guaranteed for accuracy or completeness. Users use the Service at their own responsibility.",
    "terms.s7.title": "(Personal Information)",
    "terms.s7.body": "The Company manages user personal information appropriately and does not use it for purposes other than providing and improving the Service.",
    "terms.s8.title": "(Governing Law and Jurisdiction)",
    "terms.s8.body": "These Terms shall be governed by the laws of Japan. Any disputes shall be subject to the exclusive jurisdiction of the Tokyo District Court as the court of first instance.",

    // Contact
    "footer.contact": "Contact",
    "contact.title": "Contact Us",
    "contact.subtitle": "Have a question or request? Feel free to reach out using the form below.",
    "contact.name": "Name",
    "contact.namePh": "John Smith",
    "contact.email": "Email",
    "contact.emailPh": "john@example.com",
    "contact.message": "Message",
    "contact.messagePh": "Please describe your inquiry...",
    "contact.send": "Send Message",
    "contact.required": "All fields are required",
    "contact.success": "Your message has been sent. Thank you!",
    "contact.error": "Failed to send. Please try again.",
    "contact.thankYou": "Message Sent",
    "contact.thankYouDesc": "Thank you for your message. We will review it and get back to you.",

    // Report (EN)
    "rpt.badge": "Integrated Report",
    "rpt.title": "Analysis Report",
    "rpt.subtitle": "View trade area analysis, recommended actions, ad allocation, and flyer plans on one page.",
    "rpt.address": "Address",
    "rpt.addressPh": "e.g. 1-2-3 Shibuya, Tokyo",
    "rpt.industry": "Industry",
    "rpt.industryPh": "e.g. Hair salon, Cafe",
    "rpt.storeName": "Store name (optional)",
    "rpt.storeNamePh": "e.g. Hair Salon BLOOM",
    "rpt.budget": "Monthly budget (optional)",
    "rpt.budgetPh": "e.g. ¥100,000",
    "rpt.target": "Target (optional)",
    "rpt.targetPh": "e.g. Women aged 20-30",
    "rpt.generating": "Generating report...",
    "rpt.generate": "Generate Report",
    "rpt.pdfDownload": "Download PDF",
    "rpt.errAddress": "Please enter an address",
    "rpt.errIndustry": "Please enter an industry",
    "rpt.success": "Report completed",
    "rpt.error": "Failed to generate report",
    "rpt.errorTitle": "Report generation failed",
    "rpt.loadingMsg": "Running 3 AI analyses simultaneously...",
    "rpt.sArea": "Trade Area Analysis",
    "rpt.areaName": "Area",
    "rpt.pop": "Est. Population",
    "rpt.hh": "Est. Households",
    "rpt.mainTarget": "Primary Target",
    "rpt.compEnv": "Competitive Environment",
    "rpt.sActions": "Recommended Actions",
    "rpt.recommended": "Recommended",
    "rpt.sBudget": "Ad Budget Allocation",
    "rpt.monthlyBudget": "Monthly Budget",
    "rpt.total": "Total",
    "rpt.monthlyTotal": "Monthly Total",
    "rpt.expectedROAS": "Expected ROAS",
    "rpt.sFlyer": "Flyer Plan",
    "rpt.totalQty": "Total Quantity",
    "rpt.totalCost": "Total Cost",
    "rpt.responseRate": "Expected Response Rate",
    "rpt.expectedROI": "Expected ROI",
    "rpt.recQty": "Recommended Qty",
    "rpt.targetLabel": "Target",

    // NotFound
    "notFound.title": "Page not found",
    "notFound.back": "Back to Home",

    // Pricing
    "pricing.badge": "Pricing",
    "pricing.title": "Choose Your Plan",
    "pricing.subtitle": "Start free and upgrade as needed.",
    "pricing.month": "month",
    "pricing.currentPlan": "Current Plan",
    "pricing.upgrade": "Upgrade to Pro",
    "pricing.manage": "Manage Subscription",
    "pricing.error": "An error occurred. Please try again.",
    "pricing.free.name": "Free",
    "pricing.free.desc": "Try key features for free",
    "pricing.free.f1": "Up to 3 diagnoses per month",
    "pricing.free.f2": "Basic trade area analysis",
    "pricing.free.f3": "Promo text generation",
    "pricing.free.f4": "PDF export",
    "pricing.pro.name": "Pro",
    "pricing.pro.desc": "Unlimited plan for serious use",
    "pricing.pro.f1": "Unlimited diagnoses & analyses",
    "pricing.pro.f2": "Census-linked trade area analysis",
    "pricing.pro.f3": "Flyer distribution planning",
    "pricing.pro.f4": "Auto-generated ad proposals",
    "pricing.pro.f5": "Integrated media plan",
    "pricing.pro.f6": "Priority support",

    // Common
    "common.required": "Required",
    "common.optional": "Optional",
    "common.enterAddress": "Please enter an address",
    "common.enterIndustry": "Please enter an industry",
    "common.copied": "Copied",

    // Agency Dashboard (extra keys)
    "agency.newDiag": "New Diagnosis",
    "agency.totalItems": "Total Projects",
    "agency.pending": "Processing",
    "agency.status": "Status",
    "agency.all": "All",
    "agency.statusPending": "Processing",
    "agency.noItems": "No matching projects found",
    "agency.typeDiag": "Diagnosis",
    "agency.detail": "Details",

    // Location Match (extra keys)
    "loc.industryPh": "e.g. Hair salon, Café, Tutoring",
    "loc.budget": "Budget Scale (optional)",
    "loc.budgetPh": "e.g. ¥5M initial, ¥300K/month",
    "loc.location": "Preferred Area / Current Location (optional)",
    "loc.locationPh": "e.g. Central Tokyo, Osaka area",
    "loc.target": "Target Audience (optional)",
    "loc.targetPh": "e.g. Women 20-30, Families",
    "loc.service": "Service Description",
    "loc.servicePh": "e.g. Organic healthy café with takeout and dine-in options.",
    "loc.prefs": "Other Preferences (optional)",
    "loc.prefsPh": "e.g. Within 5 min walk from station, rent under ¥300K/month",
    "loc.pdfDownload": "Download PDF",
    "loc.errIndustry": "Please enter an industry",
    "loc.errService": "Please enter a service description",
    "loc.success": "Area matching analysis completed",
    "loc.error": "Analysis failed",
    "loc.summaryTitle": "Analysis Summary",
    "loc.aiRecommend": "AI's Top Recommendation",
    "loc.budgetGuide": "Est. Initial Investment",
    "loc.ranking": "Recommended Area Ranking",
    "loc.pts": "pts",
    "loc.population": "Est. Population",
    "loc.rent": "Rent Estimate",
    "loc.tabStore": "Store",
    "loc.tabAd": "Ads",
    "loc.tabFlyer": "Flyers",
    "loc.thArea": "Area",
    "loc.thScore": "Score",
    "loc.thComp": "Competition",
    "loc.thTarget": "Target Fit",
    "loc.thCost": "Cost Efficiency",
    "loc.thGrowth": "Growth Potential",

    // Media Plan (extra keys)
    "media.address": "Store Location",
    "media.addressPh": "e.g. 1 Jinnan, Shibuya, Tokyo",
    "media.industryPh": "e.g. Hair salon, Tutoring",
    "media.storeNamePh": "e.g. Hair Salon BLOOM",
    "media.budget": "Monthly Budget (optional)",
    "media.budgetPh": "e.g. ¥100,000",
    "media.target": "Target Audience (optional)",
    "media.targetPh": "e.g. Families with children aged 30-40",
    "media.pdfDownload": "Download PDF",
    "media.errAddress": "Please enter an address",
    "media.errIndustry": "Please enter an industry",
    "media.success": "Media plan completed",
    "media.error": "Failed to generate plan",
    "media.copied": "Copied",
    "media.tabMeta": "Meta Ads",
    "media.tabGoogle": "Google Ads",
    "media.tabFlyer": "Flyers",
    "media.expectedCPM": "Expected CPM / CTR",
    "media.noMeta": "No Meta Ads data",
    "media.expectedCTR": "Expected CTR / CPA",
    "media.keywords": "Recommended Keywords",
    "media.adCopy": "Ad Copy",
    "media.noGoogle": "No Google Ads data",
    "media.responseRate": "Expected Response Rate",
    "media.households": "Households",
    "media.timing": "Distribution Timing",
    "media.catchcopy": "Catchphrase Ideas",
    "media.noFlyer": "No flyer data",

    // Store Candidates (extra keys)
    "sc.storeNamePh": "e.g. Café Mocha Shibuya",
    "sc.industryPh": "e.g. Café / Coffee shop",
    "sc.addressPh": "e.g. 1-2-3 Dogenzaka, Shibuya, Tokyo",
    "sc.lat": "Latitude (optional)",
    "sc.latPh": "e.g. 35.6595",
    "sc.lng": "Longitude (optional)",
    "sc.lngPh": "e.g. 139.7004",
    "sc.memoPh": "e.g. Near station rotary, high foot traffic. 2 competing cafés nearby.",
    "sc.errName": "Please enter a store name",
    "sc.errIndustry": "Please enter an industry",
    "sc.errAddress": "Please enter an address",
    "sc.created": "Store candidate registered",
    "sc.empty": "No candidates yet",
    "sc.emptyDesc": "Register areas you're considering for new stores.",

    // Store Input (extra keys)
    "si.storeNamePh": "e.g. Café Mocha Shibuya",
    "si.industryPh": "e.g. Café / Coffee shop",
    "si.addressPh": "e.g. 1-2-3 Dogenzaka, Shibuya, Tokyo",
    "si.stationPh": "e.g. 5 min walk from Shibuya Station",
    "si.targetPh": "e.g. 20-30 year old professionals, freelancers",
    "si.strengthsPh": "e.g. Fresh-roasted coffee, free Wi-Fi, power outlets",
    "si.concernsPh": "e.g. Weak weekday daytime traffic, not using social media",
    "si.budget": "Monthly Ad/Promo Budget",
    "si.budgetPh": "e.g. ¥50,000 - ¥100,000",
    "si.competitorsPh": "e.g. Starbucks Shibuya, Tully's Dogenzaka",
    "si.media": "Preferred Media (multiple)",
    "si.analyzing": "AI analyzing… (approx. 30 seconds)",
    "si.start": "Start Diagnosis",
    "si.errName": "Please enter a store name",
    "si.errIndustry": "Please enter an industry",
    "si.errAddress": "Please enter an address",
    "si.limitMsg": "Monthly free diagnosis limit (3 times) reached. Please upgrade to Pro.",
    "si.complete": "Diagnosis complete!",
    "si.error": "Failed to start diagnosis",
    "si.times": " times",

    // PromoText tabs
    "promo.tabGBP": "Google Business Profile",
    "promo.tabIG": "Instagram",
    "promo.tabX": "X",
    "promo.tabFlyer": "Flyer",
    "promo.tabLINE": "LINE",
    "promo.tabAdHeadline": "Ad Headlines",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("app-language");
    return (saved === "en" || saved === "ja") ? saved : "ja";
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("app-language", lang);
  }, []);

  const t = useCallback((key: string): string => {
    return translations[language][key] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
